### ISSUE TITLE
Setting UI Localization issue (Japanese)

### ISSUE THREAD

**Issue by noriokaki** [microsoft/terminal#9846]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

 open setting UI

### Actual Behavior

![image](https://user-images.githubusercontent.com/12603061/114965040-cf087900-9eaa-11eb-91cb-e3606f016581.png)

"役職"  is probably an error in the name of the "タブタイトル名"(tab title name).

![image](https://user-images.githubusercontent.com/12603061/114970067-a2f1f580-9eb4-11eb-98e2-58d433bab288.png)

I think "透明化" (transparency) or "透過"(translucent) would be better than "アクリル"(acrylic).

**Comment by skyline75489** [comment]
Thanks for the feedback! Would you mind making a more detailed chart from this? It would help us improve the localization.

See #9238 and #9328 for reference.

**Comment by noriokaki** [comment]
@skyline75489 
Thanks for your response. 
| key |Recommendation |
|----| ----|
|Profile_TabTitle.Header| タブタイトル名 | 
|Profile_AcrylicOpacity.Header| 不透明度 | 
|Profile_UseAcrylic.Header|透明化を有効にする |
|Profile_AcrylicHeader.Text|透明化|

**Comment by skyline75489** [comment]
We actually have a tracking issue for "traditional transparency" which is #603, so I would suggest keeping the 'acrylic' term in the translation to avoid confusion in the future. 

Feel free to list other imperfections, if you can find them 😄

**Comment by noriokaki** [comment]
I agreed about the acrylic.

| key |Recommendation |
|----| ----|
|Profile_TabTitle.Header| タブタイトル名 | 
|Profile_AcrylicOpacity.Header| アクリルの不透明度 | 
|Profile_UseAcrylic.Header|アクリル透明化を有効にする |
|Profile_AcrylicHeader.Text|アクリル透明化|
|Globals_TabWidthMode.HelpText|コンパクトは、フォーカスされていないタブをアイコンのサイズに縮小します。|
|Globals_TabWidthModeEqual.Content|均等|

**Comment by lhecker** [comment]
Tracked as MSFT:36323577.

**Comment by lhecker** [comment]
The following strings where fixed:
* `Profile_TabTitle.Header`
* `Globals_TabWidthMode.HelpText`
* `Globals_TabWidthModeEqual.Content`

There's an ongoing discussion regarding the translation for "acrylic" internally. Here's the response from the localization team:
> The English src string is “Enable acrylic”. The suggestion is adding additional term “transparency”. We should not customize translation deviating from the source strings if not absolutely necessary. Would your team’s copy writer consider updating the source string to be something like “Enable acrylic transparency” or “Enable acrylic texture” (based on the dev comment)?

**Comment by zadjii-msft** [comment]
Discussion: we thought "Enable acrylic transparency" was a fine string for now.

**Comment by lhecker** [comment]
I was about to change it to "acrylic transparency" but then I realized I should check what Microsoft uses officially...
Turns out "acrylic material" or "アクリル素材" is the proper name:
* https://docs.microsoft.com/en-us/windows/apps/design/style/acrylic
* https://docs.microsoft.com/ja-jp/windows/apps/design/style/acrylic
