### ISSUE TITLE
cannot configure starting directory in GUI when its default value is set to null

### ISSUE THREAD

**Issue by taroxd** [microsoft/terminal#9847]
### Windows Terminal version (or Windows build number)

10.0.19042.928 1.7.1033.0

### Steps to reproduce

First, Set
```
    "profiles":
    {
        "defaults":
        {
            "startingDirectory": null
        },
...
```

This makes the default starting directory to the parent process, which is my expected behaviour.

After that, however, the starting directory for individual shell cannot be configured in the GUI. The `Browse` button is grayed out. See the screenshot:
![image](https://user-images.githubusercontent.com/6070540/114979591-b9507f00-9ebd-11eb-9c4a-32e93e0e7145.png)

### Expected Behavior

The starting directory should be configurable in the GUI.

### Actual Behavior

See `Steps to reproduce`.

**Comment by skyline75489** [comment]
Does #8904 covers this?

**Comment by taroxd** [comment]
Hopefully it does. I will wait for the it to be resolved.

**Comment by zadjii-msft** [comment]
Yea, it sounds like #8904 will take care of this

/dup #8904

**Comment by DHowett** [comment]
However, what we have today in 1.7 is broken and needs to be fixed.

I'm going to use this bug to track fixing it for servicing, as I am not going to backport a design change :smile:
