### ISSUE TITLE
Draft 2019-09 schemas are not yet fully supported.(768)

### ISSUE THREAD

**Issue by g96k** [microsoft/terminal#9848]
### Windows Terminal version (or Windows build number)

Version: 1.7.1033.0

### Steps to reproduce

Those are my settings.json . If i switch to 
"https://github.com/microsoft/terminal/raw/e504bf21402bca34e45863370aad9fefd543c292/doc/cascadia/profiles.schema.json

it produced other errors regarding the settings. Its not like it affects me in any I would just prefer for my settings.json to be clear from errors.

        {
            "$schema": "https://aka.ms/terminal-profiles-schema",
            // Add custom actions and keybindings to this array.
            // To unbind a key combination from your defaults.json, set the command to "unbound".
            // To learn more about actions and keybindings, visit https://aka.ms/terminal-keybindings
            "actions": 
            [
                // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
                // These two lines additionally bind them to Ctrl+C and Ctrl+V.
                // To learn more about selection, visit https://aka.ms/terminal-selection
                {
                    "command": 
                    {
                        "action": "copy",
                        "singleLine": false
                    },
                    "keys": "ctrl+c"
                },
                {
                    "command": "paste",
                    "keys": "ctrl+v"
                },
                // Press Ctrl+Shift+F to open the search box
                {
                    "command": "find",
                    "keys": "ctrl+shift+f"
                },
                // Press Alt+Shift+D to open a new pane.
                // - "split": "auto" makes this pane open in the direction that provides the most surface area.
                // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
                // To learn more about panes, visit https://aka.ms/terminal-panes
                {
                    "command": 
                    {
                        "action": "splitPane",
                        "split": "auto",
                        "splitMode": "duplicate"
                    },
                    "keys": "alt+shift+d"
                },
                {
                    "command": 
                    {
                        "action": "newTab"
                    },
                    "keys": "ctrl+t"
                },
                {
                    "command": 
                    {
                        "action": "closeTab"
                    },
                    "keys": "ctrl+shift+w"
                }
            ],
            "copyFormatting": "none",
            "copyOnSelect": false,
            "defaultProfile": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
            "launchMode": "fullscreen",
            "profiles": 
            {
                "defaults": {},
                "list": 
                [
                    {
                        "colorScheme": "One Half Dark",
                        "commandline": "powershell.exe",
                        "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                        "hidden": false,
                        "name": "Windows PowerShell",
                    },
                    {
                        "commandline": "cmd.exe",
                        "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                        "hidden": false,
                        "name": "Command Prompt"
                    },
                    {
                        "colorScheme": "One Half Dark",
                        "fontFace": "JetBrains Mono",
                        "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                        "hidden": false,
                        "name": "Ubuntu-20.04",
                        "source": "Windows.Terminal.Wsl"
                    },
                    {
                        "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                        "hidden": false,
                        "name": "Azure Cloud Shell",
                        "source": "Windows.Terminal.Azure"
                    },
                    {
                        "colorScheme": "One Half Dark"
                    }
                ]
            },
            "schemes": 
            [
                {
                    "background": "#0C0C0C",
                    "black": "#0C0C0C",
                    "blue": "#0037DA",
                    "brightBlack": "#767676",
                    "brightBlue": "#3B78FF",
                    "brightCyan": "#61D6D6",
                    "brightGreen": "#16C60C",
                    "brightPurple": "#B4009E",
                    "brightRed": "#E74856",
                    "brightWhite": "#F2F2F2",
                    "brightYellow": "#F9F1A5",
                    "cursorColor": "#FFFFFF",
                    "cyan": "#3A96DD",
                    "foreground": "#838D8D",
                    "green": "#13A10E",
                    "name": "Campbell",
                    "purple": "#881798",
                    "red": "#C50F1F",
                    "selectionBackground": "#FFFFFF",
                    "white": "#CCCCCC",
                    "yellow": "#C19C00"
                },
                {
                    "background": "#012456",
                    "black": "#0C0C0C",
                    "blue": "#0037DA",
                    "brightBlack": "#767676",
                    "brightBlue": "#3B78FF",
                    "brightCyan": "#61D6D6",
                    "brightGreen": "#16C60C",
                    "brightPurple": "#B4009E",
                    "brightRed": "#E74856",
                    "brightWhite": "#F2F2F2",
                    "brightYellow": "#F9F1A5",
                    "cursorColor": "#FFFFFF",
                    "cyan": "#3A96DD",
                    "foreground": "#CCCCCC",
                    "green": "#13A10E",
                    "name": "Campbell Powershell",
                    "purple": "#881798",
                    "red": "#C50F1F",
                    "selectionBackground": "#FFFFFF",
                    "white": "#CCCCCC",
                    "yellow": "#C19C00"
                },
                {
                    "background": "#1C2022",
                    "black": "#282C34",
                    "blue": "#61AFEF",
                    "brightBlack": "#5A6374",
                    "brightBlue": "#61AFEF",
                    "brightCyan": "#56B6C2",
                    "brightGreen": "#98C379",
                    "brightPurple": "#C678DD",
                    "brightRed": "#E06C75",
                    "brightWhite": "#DCDFE4",
                    "brightYellow": "#E5C07B",
                    "cursorColor": "#FFFFFF",
                    "cyan": "#56B6C2",
                    "foreground": "#838D8D",
                    "green": "#98C379",
                    "name": "One Half Dark",
                    "purple": "#C678DD",
                    "red": "#E06C75",
                    "selectionBackground": "#FFFFFF",
                    "white": "#DCDFE4",
                    "yellow": "#E5C07B"
                },
                {
                    "background": "#FAFAFA",
                    "black": "#383A42",
                    "blue": "#0184BC",
                    "brightBlack": "#4F525D",
                    "brightBlue": "#61AFEF",
                    "brightCyan": "#56B5C1",
                    "brightGreen": "#98C379",
                    "brightPurple": "#C577DD",
                    "brightRed": "#DF6C75",
                    "brightWhite": "#FFFFFF",
                    "brightYellow": "#E4C07A",
                    "cursorColor": "#4F525D",
                    "cyan": "#0997B3",
                    "foreground": "#383A42",
                    "green": "#50A14F",
                    "name": "One Half Light",
                    "purple": "#A626A4",
                    "red": "#E45649",
                    "selectionBackground": "#FFFFFF",
                    "white": "#FAFAFA",
                    "yellow": "#C18301"
                },
                {
                    "background": "#002B36",
                    "black": "#002B36",
                    "blue": "#268BD2",
                    "brightBlack": "#073642",
                    "brightBlue": "#839496",
                    "brightCyan": "#93A1A1",
                    "brightGreen": "#586E75",
                    "brightPurple": "#6C71C4",
                    "brightRed": "#CB4B16",
                    "brightWhite": "#FDF6E3",
                    "brightYellow": "#657B83",
                    "cursorColor": "#FFFFFF",
                    "cyan": "#2AA198",
                    "foreground": "#839496",
                    "green": "#859900",
                    "name": "Solarized Dark",
                    "purple": "#D33682",
                    "red": "#DC322F",
                    "selectionBackground": "#FFFFFF",
                    "white": "#EEE8D5",
                    "yellow": "#B58900"
                },
                {
                    "background": "#FDF6E3",
                    "black": "#002B36",
                    "blue": "#268BD2",
                    "brightBlack": "#073642",
                    "brightBlue": "#839496",
                    "brightCyan": "#93A1A1",
                    "brightGreen": "#586E75",
                    "brightPurple": "#6C71C4",
                    "brightRed": "#CB4B16",
                    "brightWhite": "#FDF6E3",
                    "brightYellow": "#657B83",
                    "cursorColor": "#002B36",
                    "cyan": "#2AA198",
                    "foreground": "#657B83",
                    "green": "#859900",
                    "name": "Solarized Light",
                    "purple": "#D33682",
                    "red": "#DC322F",
                    "selectionBackground": "#FFFFFF",
                    "white": "#EEE8D5",
                    "yellow": "#B58900"
                },
                {
                    "background": "#000000",
                    "black": "#000000",
                    "blue": "#3465A4",
                    "brightBlack": "#555753",
                    "brightBlue": "#729FCF",
                    "brightCyan": "#34E2E2",
                    "brightGreen": "#8AE234",
                    "brightPurple": "#AD7FA8",
                    "brightRed": "#EF2929",
                    "brightWhite": "#EEEEEC",
                    "brightYellow": "#FCE94F",
                    "cursorColor": "#FFFFFF",
                    "cyan": "#06989A",
                    "foreground": "#D3D7CF",
                    "green": "#4E9A06",
                    "name": "Tango Dark",
                    "purple": "#75507B",
                    "red": "#CC0000",
                    "selectionBackground": "#FFFFFF",
                    "white": "#D3D7CF",
                    "yellow": "#C4A000"
                },
                {
                    "background": "#FFFFFF",
                    "black": "#000000",
                    "blue": "#3465A4",
                    "brightBlack": "#555753",
                    "brightBlue": "#729FCF",
                    "brightCyan": "#34E2E2",
                    "brightGreen": "#8AE234",
                    "brightPurple": "#AD7FA8",
                    "brightRed": "#EF2929",
                    "brightWhite": "#EEEEEC",
                    "brightYellow": "#FCE94F",
                    "cursorColor": "#000000",
                    "cyan": "#06989A",
                    "foreground": "#555753",
                    "green": "#4E9A06",
                    "name": "Tango Light",
                    "purple": "#75507B",
                    "red": "#CC0000",
                    "selectionBackground": "#FFFFFF",
                    "white": "#D3D7CF",
                    "yellow": "#C4A000"
                },
                {
                    "background": "#000000",
                    "black": "#000000",
                    "blue": "#000080",
                    "brightBlack": "#808080",
                    "brightBlue": "#0000FF",
                    "brightCyan": "#00FFFF",
                    "brightGreen": "#00FF00",
                    "brightPurple": "#FF00FF",
                    "brightRed": "#FF0000",
                    "brightWhite": "#FFFFFF",
                    "brightYellow": "#FFFF00",
                    "cursorColor": "#FFFFFF",
                    "cyan": "#008080",
                    "foreground": "#C0C0C0",
                    "green": "#008000",
                    "name": "Vintage",
                    "purple": "#800080",
                    "red": "#800000",
                    "selectionBackground": "#FFFFFF",
                    "white": "#C0C0C0",
                    "yellow": "#808000"
                }
            ]
        }

### Actual Behavior

.

**Comment by zadjii-msft** [comment]
That sounds like an issue with whoever is parsing this schema. I'm guessing VsCode? Because the _terminal_ certainly isn't the application to be displaying that message. If it is VsCode, then this should be /dup https://github.com/microsoft/vscode/issues/98724. If it's any other application, then you should file an issue on _their_ issue tracker.
