### ISSUE TITLE
Dropdown opens upwards

### ISSUE THREAD

**Issue by mpela81** [microsoft/terminal#9849]
### Windows Terminal version (or Windows build number)

Windows Terminal Version: 1.7.1033.0

### Steps to reproduce

Click the button to open the dropdown. Ensure there is enough space for the dropdown to open down.

### Expected Behavior

The dropdown opens downwards.

### Actual Behavior

The dropdown opens upwards.

![immagine](https://user-images.githubusercontent.com/1140981/114993414-150a1080-9e9c-11eb-8737-5f60fcde6dc2.png)

**Comment by mpela81** [comment]
screen:
![immagine](https://user-images.githubusercontent.com/1140981/114993302-f7d54200-9e9b-11eb-86a1-fdfe2140d0bf.png)

**Comment by skyline75489** [comment]
Yeah this is /dup #8924

**Comment by mpela81** [comment]
oh thanks, didn't find it
