### ISSUE TITLE
Remember last open tabs with their current directory and profile 

### ISSUE THREAD

**Issue by alrz** [microsoft/terminal#9850]
### Description 
This is similar to "Continue where you left off on startup" option in browsers and it would make "do you want to close all tabs" dialog obsolete. Note that if you're opening a new tab with "Open in Windows Terminal", for example, the previous tabs should be still opened with the focus on the new tab.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22Remember+open+tabs%22+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #766 for more discussion.

/dup #766

**Comment by alrz** [comment]
Sorry, was just about to close as dup (https://github.com/microsoft/terminal/issues/961 is another)
