### ISSUE TITLE
Reload tabs as Admin/Non-admin

### ISSUE THREAD

**Issue by Cortana-117** [microsoft/terminal#9851]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
You gotta give us actual information. We can't do anything with a blank issue like this. Feel free to edit the OP and we can reopen the discussion.

**Comment by Cortana-117** [comment]
> You gotta give us actual information. We can't do anything with a blank issue like this. Feel free to edit the OP and we can reopen the discussion.

Hi,
i was just editing my comment for a second. it's good now.

**Comment by Cortana-117** [comment]
> You gotta give us actual information. We can't do anything with a blank issue like this. Feel free to edit the OP and we can reopen the discussion.

Hi, i was temporarily editing my post, it's good now.
