### ISSUE TITLE
Show background image in Windows Terminal when using ClearType text antialiasing option

### ISSUE THREAD

**Issue by Cortana-117** [microsoft/terminal#9852]
### Windows Terminal version (or Windows build number)

1.8.1032.0 (Windows 10 21H1 build 19043.928)

### Steps to reproduce

Go to Windows Terminal settings, PowerShell or CMD profiles, Appearance tab, set the background to a custom picture or use desktop background, then go to Advanced tab, set text-antialiasing to ClearType.

### Expected Behavior

The background image should be visible when using "ClearType", just like when we use "Grayscale" or "Aliased" text antialiasing.

### Actual Behavior

you will see the background is no longer visible and instead a dark shadow is displayed behind the text.

![image](https://user-images.githubusercontent.com/72892766/115023162-ec8b1200-9ead-11eb-9d16-833ee92c07e5.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+cleartype) when filing new issues. This is already being tracked by another issue on our repo - please refer to #5703 for more discussion.

/dup #5703
