### ISSUE TITLE
Add animation to the "close all tabs" prompt

### ISSUE THREAD

**Issue by cl-ement05** [microsoft/terminal#9853]
# Description of the new feature/enhancement
So this is more a design enhancement than a feature request. I think it would be great to animate the "are you sure you want to close all tabs" prompt. Because right now it simply appears or disappears which is kind of _ugly_.

I would animate it like the zoom in animation of PowerPoint when it spawns and I user clicks on cancel, rather than simply disappearing, I would make a "zoom out animation".

To explain more clearly what I am thinking about : start the Firefox browser and open multiples tabs, then try to close Firefox. The same "close all tabs ?" prompt should appear with an animation. So I believe the way Firefox makes it pop up appear and disappear is elegant and should be integrated to windows terminal

I have no idea however of how it could be implemented sorry :-

**Comment by zadjii-msft** [comment]
This is a good idea, but would definitely require work from WinUI itself. I've moved the request to /dup https://github.com/microsoft/microsoft-ui-xaml/issues/4843
