### ISSUE TITLE
Changing font and font size

### ISSUE THREAD

**Issue by phand00** [microsoft/terminal#9855]
### Windows Terminal version (or Windows build number)

1.8

### Other Software

Changing Font and Font size with Ubuntu WSL2 and always revert to default.
Tried to change directly in settings.json file and it's not working

Was able to change the font and font size for powershell, cmd only

### Steps to reproduce

Try to change font to anything else
try to change font size to anything else

### Expected Behavior

able to change font and font size on other terminal

### Actual Behavior

always revert to default size 12 and default font Cacadia Mono

**Comment by zadjii-msft** [comment]
Could you be more specific? Are you using the settings UI or the json file?

**Comment by phand00** [comment]
settings UI

**Comment by zadjii-msft** [comment]
Hmmm. This sounds suspiciously like #9775. When you hit "save", does the font size reset when the page reloads, or does it reset when you relaunch the app? Just trying to make sure we got this scenario totally understood ☺️

**Comment by phand00** [comment]
When I hit save, the settings revert to default but only for Ubuntu (WSL/WSL2) terminals. But it's working for powershell and cmd terminals

**Comment by zadjii-msft** [comment]
@phand00 Could you share your `settings.json` file? That might help us figure out what's going on here.

**Comment by phand00** [comment]
// This file was initially generated by Windows Terminal 1.1.2233.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.
// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
	"$schema"            : "https://aka.ms/terminal-profiles-schema",
	"confirmCloseAllTabs": true,
	// If enabled, formatted data is also copied to your clipboard
	"copyFormatting": false,
	// You can add more global application settings here.
	// To learn more about global settings, visit https://aka.ms/terminal-global-settings
	// If enabled, selections are automatically copied to your clipboard.
	"copyOnSelect": true,
	//"defaultProfile": "{2c4de342-38b7-51cf-b940-2309a097f518}",
	"defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
	// Add custom keybindings to this array.
	// To unbind a key combination from your defaults.json, set the command to "unbound".
	// To learn more about keybindings, visit https://aka.ms/terminal-keybindings
	"keybindings": 
	[
		// Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
		// These two lines additionally bind them to Ctrl+C and Ctrl+V.
		// To learn more about selection, visit https://aka.ms/terminal-selection
		{
			"command": 
			{
				"action"    : "copy",
				"singleLine": false
			},
			"keys": "ctrl+c"
		},
		{
			"command": "paste",
			"keys"   : "ctrl+shift+v"
		},
		// Press Ctrl+Shift+F to open the search box
		{
			"command": "find",
			"keys"   : "ctrl+shift+f"
		},
		// Press Alt+Shift+D to open a new pane.
		// - "split": "auto" makes this pane open in the direction that provides the most surface area.
		// - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
		// To learn more about panes, visit https://aka.ms/terminal-panes
		{
			"command": 
			{
				"action"   : "splitPane",
				"split"    : "auto",
				"splitMode": "duplicate"
			},
			"keys": "alt+shift+d"
		}
	],
	// A profile specifies a command to execute paired with information about how it should look and feel.
	// Each one of them will appear in the 'New Tab' dropdown,
	//   and can be invoked from the commandline with `wt.exe -p xxx`
	// To learn more about profiles, visit https://aka.ms/terminal-profile-settings
	"profiles": 
	{
		"defaults": 
		{
			"antialiasingMode": "cleartype",
			//"useAcrylic"      : true,
			//"acrylicOpacity"  : 0.9,
			//"colorScheme": "Tango Dark",
			"colorScheme": "Molokai",
			//"fontFace"   : "Consolas",
			"fontFace": "Cascadia Code PL",
			// Put settings here that you want to apply to all profiles.
			//"fontSize": 8
			"fontSize": 9
		},
		//"colorScheme": "Tango Dark"
		//"colorScheme": "One Half Dark"
		"list": 
		[
			{
				"commandline": "cmd.exe /k",
				// Make changes here to the cmd.exe profile.
				"guid"  : "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
				"hidden": false,
				"name"  : "Command Prompt"
			},
			{
				//"colorScheme": "Campbell Powershell",
				"commandline": "powershell.exe",
				// Make changes here to the powershell.exe profile.
				"guid"    : "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
				"hidden"  : false,
				"fontFace": "Cascadia Code PL",
				"name"    : "Windows PowerShell"
			},
			{
				"commandline": "pwsh.exe",
				// Make changes here to the pwsh.exe profile.
				"guid"  : "{3a0afad7-6642-4be9-8d71-6fe5cdf9d2c1}",
				"hidden": true,
				"name"  : "PowerShell Core"
			},
			{
				"commandline": "wsl.exe --distribution Ubuntu",
				"guid"       : "{2c4de342-38b7-51cf-b940-2309a097f518}",
				"hidden"     : false,
				//"name"       : "Ubuntu 20.04 (WSL v2)",
				//"name"  : "WSL - Ubuntu 20.04 (WSL v2)",
				"name"  : "WSL2 Shell - 20.04",
				"source": "Windows.Terminal.Wsl"
			},
			{
				"commandline": "wsl.exe --distribution Ubuntu-18.04",
				"guid"       : "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
				"hidden"     : false,
				//"name"       : "Ubuntu 18.04 (WSL v1)",
				"name"  : "WSL1 Shell - 18.04",
				"source": "Windows.Terminal.Wsl"
			},
			{
				"commandline": "lua",
				"guid"       : "{b12b6fa6-5c7a-4746-a5fb-7302d0222f76}",
				"hidden"     : true,
				"icon"       : "ms-appdata:///roaming/lua.png",
				"name"       : "Lua shell"
			},
			{
				"commandline": "python",
				"guid"       : "{a3b08b37-0606-40c0-aab2-69e49c53e148}",
				"hidden"     : true,
				"icon"       : "ms-appdata:///roaming/python-96.png",
				"name"       : "Python shell"
			},
			{
				"commandline": "node",
				"guid"       : "{6c874940-95a0-4672-b952-591f9a20c167}",
				"hidden"     : true,
				"icon"       : "ms-appdata:///roaming/js.png",
				"name"       : "NodeJS shell",
				"source"     : "Windows.Terminal.Wsl"
			},
			{
				"commandline": "ssh -t phad9401@ps01",
				//"commandline": "ssh -t phad9401@ps01 -i %userprofile%\\.ssh\\id_rsa_phad9401",
				//"commandline": "wsl.exe --distribution Ubuntu-20.04 ssh phad9401@ps01.sti.usherbrooke.ca",
				"guid"  : "{7ce28204-d77a-4a43-b215-af8f1d7f4d93}",
				"hidden": false,
				"icon"  : "ms-appdata:///roaming/ssh.png",
				"name"  : "PS01"
			},
			{
				"commandline": "ssh -t phad9401@ds01",
				//"commandline": "wsl.exe --distribution Ubuntu-20.04 ssh phad9401@ps01.sti.usherbrooke.ca",
				"guid"  : "{a4df5908-673c-40ab-a2f8-41b8ee011212}",
				"hidden": false,
				"icon"  : "ms-appdata:///roaming/ssh.png",
				"name"  : "DS01"
			},
//			{
//				"commandline": "ssh -t phad9401@ts01",
//				"guid"       : "{0637b323-c92c-451d-b27d-17dc1643886a}",
//				"hidden"     : true,
//				"icon"       : "ms-appdata:///roaming/ssh.png",
//				"name"       : "TS01"
//			},
			{
				"guid"  : "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
				"hidden": false,
				"name"  : "Azure Cloud Shell",
				"source": "Windows.Terminal.Azure"
			},
			{
				"background" : "#350425",
				"commandline": "multipass shell",
				"cursorShape": "filledBox",
				"fontFace"   : "Ubuntu Mono",
				"guid"       : "{aaaa9e6d-1e09-4be6-b76c-82b4ba1885fb}",
				"hidden"     : false,
				"historySize": 50000,
				"icon"       : "C:/Program Files/Multipass/bin/multipass_wt.ico",
				"name"       : "Multipass"
			}
		]
	},
	// Add custom color schemes to this array.
	// To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
	"schemes": 
	[
		{
			"background"  : "#000000",
			"black"       : "#000000",
			"blue"        : "#2186ec",
			"brightBlack" : "#000000",
			"brightBlue"  : "#2f9ded",
			"brightCyan"  : "#19cde6",
			"brightGreen" : "#25c141",
			"brightPurple": "#f97137",
			"brightRed"   : "#f841a0",
			"brightWhite" : "#ffffff",
			"brightYellow": "#fdf454",
			"cyan"        : "#12c3e2",
			"foreground"  : "#dad9c7",
			"green"       : "#1ebb2b",
			"name"        : "Synthwave",
			"purple"      : "#f85a21",
			"red"         : "#f6188f",
			"white"       : "#ffffff",
			"yellow"      : "#fdf834"
		},
		{
			"background"  : "#111213",
			"black"       : "#323232",
			"blue"        : "#43a5d5",
			"brightBlack" : "#323232",
			"brightBlue"  : "#43a5d5",
			"brightCyan"  : "#8ec43d",
			"brightGreen" : "#8ec43d",
			"brightPurple": "#8b57b5",
			"brightRed"   : "#c22832",
			"brightWhite" : "#ffffff",
			"brightYellow": "#e0c64f",
			"cyan"        : "#8ec43d",
			"foreground"  : "#cacecd",
			"green"       : "#8ec43d",
			"name"        : "Seti",
			"purple"      : "#8b57b5",
			"red"         : "#c22832",
			"white"       : "#eeeeee",
			"yellow"      : "#e0c64f"
		},
		{
			"background"  : "#0c0c0c",
			"black"       : "#1a1a1a",
			"blue"        : "#9d65ff",
			"brightBlack" : "#625e4c",
			"brightBlue"  : "#9d65ff",
			"brightCyan"  : "#58d1eb",
			"brightGreen" : "#98e024",
			"brightPurple": "#f4005f",
			"brightRed"   : "#f4005f",
			"brightWhite" : "#f6f6ef",
			"brightYellow": "#e0d561",
			"cyan"        : "#58d1eb",
			"foreground"  : "#d9d9d9",
			"green"       : "#98e024",
			"name"        : "Monokai Remastered",
			"purple"      : "#f4005f",
			"red"         : "#f4005f",
			"white"       : "#c4c5b5",
			"yellow"      : "#fd971f"
		},
		{
			"background"  : "#121212",
			"black"       : "#121212",
			"blue"        : "#0443ff",
			"brightBlack" : "#838383",
			"brightBlue"  : "#0443ff",
			"brightCyan"  : "#51ceff",
			"brightGreen" : "#b1e05f",
			"brightPurple": "#f200f6",
			"brightRed"   : "#f6669d",
			"brightWhite" : "#ffffff",
			"brightYellow": "#fff26d",
			"cyan"        : "#01b6ed",
			"foreground"  : "#f9f9f9",
			"green"       : "#98e123",
			"name"        : "Monokai Vivid",
			"purple"      : "#f800f8",
			"red"         : "#fa2934",
			"white"       : "#ffffff",
			"yellow"      : "#fff30a"
		},
		{
			"background"  : "#121212",
			"black"       : "#121212",
			"blue"        : "#1080d0",
			"brightBlack" : "#555555",
			"brightBlue"  : "#00afff",
			"brightCyan"  : "#51ceff",
			"brightGreen" : "#b1e05f",
			"brightPurple": "#af87ff",
			"brightRed"   : "#f6669d",
			"brightWhite" : "#ffffff",
			"brightYellow": "#fff26d",
			"cyan"        : "#43a8d0",
			"foreground"  : "#bbbbbb",
			"green"       : "#98e123",
			"name"        : "Molokai",
			"purple"      : "#8700ff",
			"red"         : "#fa2573",
			"white"       : "#bbbbbb",
			"yellow"      : "#dfd460"
		},
		{
			"background"  : "#000000",
			"black"       : "#000000",
			"blue"        : "#c48dff",
			"brightBlack" : "#555555",
			"brightBlue"  : "#5555ff",
			"brightCyan"  : "#55ffff",
			"brightGreen" : "#55ff55",
			"brightPurple": "#ff55ff",
			"brightRed"   : "#ff5555",
			"brightWhite" : "#ffffff",
			"brightYellow": "#ffff55",
			"cyan"        : "#67d9f0",
			"foreground"  : "#bbbbbb",
			"green"       : "#a6e32d",
			"name"        : "Mathias",
			"purple"      : "#fa2573",
			"red"         : "#e52222",
			"white"       : "#f2f2f2",
			"yellow"      : "#fc951e"
		}
	],
	"tabWidthMode": "titleLength",
	"theme"       : "dark"
}

**Comment by zadjii-msft** [comment]
We've managed to track down a minimal repro of this. We're now tracking this in #9962. Thanks for the help!

/dup #9962
