### ISSUE TITLE
[Terminal Settings UI] Change the option 'Open JSON file' to 'Advanced Settings'

### ISSUE THREAD

**Issue by Rahul-Dixit** [microsoft/terminal#9856]
# Description of the new idea

In the terminal settings UI, there is an option 'Open JSON file' that helps us to configure the terminal in an advanced manner. However from a design perspective, the option label 'Open JSON file' looks quite unprofessional. It can be changed to something like 'Advanced settings' or 'Advanced mode'.

Let me support my argument with an example:
The Windows 10 settings app allows us to configure various aspects of Windows in a simplified manner, but the advanced settings are present in Control Panel. For these advanced settings, usually a link named 'Advanced properties' is provided on the Settings page(s) that takes us to their respective Control Panel applet. Note that they did not use the term 'Open Control Panel' or something like that.

# Proposed technical implementation details

The option label 'Open JSON file' should be changed to 'Advanced settings'. This also makes it more consistent with other elements of Windows. This is a relatively small change but is a significant improvement. It guides the new users that the option contains those settings which cannot be normally configured through the UI.

**Comment by zadjii-msft** [comment]
I kinda disagree, and here's my reasoning. When you go to the Control Panel, you're still getting a UI experience. However, with the "advanced settings" of the terminal, all of a sudden another app is opening to edit a .json file. That's maybe a little unexpected now. There's already been an endless stream of users confused with the old experience, where clicking on Settings would open up Visual Studio to edit the json file. I think it's actually clearer to indicate to the user that you're going to be opening a json file when you click that button.

**Comment by Rahul-Dixit** [comment]
But that is not much of an issue. I have two things to say:

- Tools like Windows Terminal are mostly, if not completely, used by system administrators and developers. They will not get panicked if suddenly Notepad opens up with a .json file. And you say that the switch from Settings to Control Panel is justified because Control Panel provides a UI experience. But you forgot that Control Panel is meant for everyday home and office users, but Windows Terminal is not. I agree to the fact that they may feel uncomfortable if they suddenly see a .json file, but in reality they will not even open the Windows Terminal app. All the existing users of Windows Terminal know very well about the settings.json file.
- And as far as new users are concerned, we do not expect them to make changes to the terminal using the .json file (and that's why we made the Settings page, right?). And unless we completely remove the settings.json file, it would always be unexpected to see the .json file. Since there is no plan to remove it in the near future, this issue is irrelevant as one would definitely have to use it some day or the other. And even if we don't change its name we will not be able to remove that confusion entirely.

I hope you got my point.

**Comment by zadjii-msft** [comment]
After discussion with the team we've decided that we're gonna keep it as "Open in JSON". VsCode, for example, has very similar functionality and naming. Thanks for the suggestion!
