### ISSUE TITLE
`move-focus` doesn't work after splitting

### ISSUE THREAD

**Issue by jack1142** [microsoft/terminal#9858]
### Windows Terminal version (or Windows build number)

10.0.19041.867, 1.7.1033.0

### Steps to reproduce

1. Open new tab without any split panes in Windows Terminal
2. Run this command in the tab:
```
wt sp -V cmd /C "echo hello && pause" ; mf left
```
3. Observe

### Expected Behavior

I expected a split pane to be created and a focus to still remain on the previously focused pane:
![image](https://user-images.githubusercontent.com/6032823/115040330-9b8d1500-9ed1-11eb-87c3-d54acc7b07ae.png)

### Actual Behavior

The split pane *was created* but a focus switched to the new pane:
![image](https://user-images.githubusercontent.com/6032823/115041476-d6dc1380-9ed2-11eb-92db-2f5d76efbf9d.png)

**Comment by jack1142** [comment]
A clever workaround for this is to run a `wt mf left` command *inside* the new pane like this:
```
wt sp -V cmd /C "wt mf left && echo hello && pause"
```

**Comment by zadjii-msft** [comment]
Weirdly enough, this is tracked in #6586. `move-focus` works great _during_ the startup, while the commands are being processed, but unfortunately focus still gets yeeted at one of the panes randomly once startup is finished 😞 

/dup #6586
