### ISSUE TITLE
Add switch to ColorTool to write the color scheme to the Windows Terminal profiles.json

### ISSUE THREAD

**Issue by DJackman123** [microsoft/terminal#986]
# Summary of the new feature/enhancement

ColorTool should be extended to allow it to write the color scheme to the Windows Terminal profiles.json file so it can work for users of both conhost and the new Terminal.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
I've mentioned before (somewhere) how I want to add tighter integration between the two. I was imagining a `wt.exe` flag that would attempt to import all your schemes from colortool. We can use this thread to track that feature.

**Comment by DHowett-MSFT** [comment]
For now, though, you can use `ColorTool` in xterm mode to set the _current_ WT theme.

**Comment by DJackman123** [comment]
I'm interested in contributing here, but would like to lock down the best approach.  I'm seeing a couple of options:

1. Add a -t/--terminal switch that writes the scheme to the Windows Terminal profiles.json _instead_ of current or defaults.  This would make the --both switch confusing without some clarifying docs.

2. Change the -o/--output switch so it can write the current console colors to either the specified ini file or the Windows Terminal profiles.json file.  Then the path to import a new color scheme into Terminal would be to apply the scheme to the current console using -x then using -o to output the scheme to profiles.json.

What do you think?

**Comment by zadjii-msft** [comment]
I'm mildly concerned about writing it directly to the profiles.json file. I'm not sure we have a consistent way of knowing exactly where it will be from outside the package. Plus, if you're running dev builds of the terminal, you'll probably actually have _two_ profiles.json files, one for the "Dev Build" and one for the "Preview Build" (which isn't available yet).

I'd probably prefer some implementation between the two, where we write the json-compatible scheme to stdout, and then the user can copy that into their profiles.json file manually,

**Comment by DJackman123** [comment]
Understood.  My current thinking after playing with it over the weekend for a bit is to add a -t/--terminal switch that will work like the -x/--xterm switch does now and outputs the scheme to stdout in a json-like format such that the user can copy/paste the text into their profiles.json.
I decided against outputting the current console colors (after using -x on a scheme) because when applying the colors via -x the scheme's foreground and background colors are ignored.

**Comment by sba923** [comment]
Note that the generated JSON does use the "foreground" color from the `.itermcolors` file, whereas applying the same file via `colortool -b` results in CMD or PowerShell 7 to use "black" as the background color.

IOW, if you want the same result within Windows Terminal as outside Windows Terminal, you need to overwrite the "foreground" value with that for the "black" entry.

**Comment by sba923** [comment]
Another comment: when invoking `colortool -t c:\usr\wbin\schemes\Ubuntu.itermcolors` the resulting JSON includes:

````
 "name": "c:\usr\wbin\schemes\Ubuntu"
````

whereas I would have just emitted:

````
 "name": "Ubuntu"
````

but one can argue that's a matter of taste, and can (has to?) be manually edited after pasting into the Windows Terminal settings file...
