### ISSUE TITLE
Terminal settings UI should open in a new window

### ISSUE THREAD

**Issue by segundovolante** [microsoft/terminal#9863]
# Description of the new feature/enhancement

Instead of opening in a tab I would prefer it to have it opened in a different window, this allows the user for example to save the new appearance settings and see the results without constantly switching tabs.

# Proposed technical implementation details (optional)

Open settings in a new window or dialog box similar to cmd settings, iterm from mac , terminal from linux

**Comment by kellytrinh** [comment]
agree with above, also could have the settings UI window respond to 'esc' to close.  Right now new pane is annoying (it doesn't 'belong' with all the other terminal panes) and making it go away is annoying.

**Comment by zadjii-msft** [comment]
FYI, we're currently working on adding a preview of the control directly to the settings UI: (#9527)

![i](https://user-images.githubusercontent.com/26824113/113629299-17a67380-961b-11eb-9752-7758b12b6975.gif)


This was originally discussed when we first started working on the settings UI here: https://github.com/microsoft/terminal/blob/main/doc/specs/%231564%20-%20Settings%20UI/spec.md#we-also-considered-launch-in-a-new-window. It doesn't look like that spec got updated to say _why_ we decided against it, so I'll leave that as a question for @cinnamon-msft to elaborate upon ☺️

**Comment by cinnamon-msft** [comment]
I believe we decided to keep it as a tab inside the terminal because VS Code has a similar behavior, plus once we get tab tear-off you could always pull the settings tab out. 😊 We also planned on having the preview window, which makes it a bit easier to use when it's a tab.

**Comment by segundovolante** [comment]
Oh that's great to hear. When is the tab tear off coming out? 

I think the preview might also do it but might need to be smart enough to preview either your current tab or a tab with your plugins like oh-my-posh.

**Comment by zadjii-msft** [comment]
>  When is the tab tear off coming out?

Eventually. There's a ton of work that needs to be done to support tear off. The main thread tracking that is #1256, there's a megathread in #5000, and I'm tracking the individual pieces in https://github.com/microsoft/terminal/projects/5.
