### ISSUE TITLE
Intergrate Cmder + Windows 10 Terminal = strange background color bug

### ISSUE THREAD

**Issue by buinguyenhoangtho** [microsoft/terminal#9865]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

Cmder-Console Emulator

### Steps to reproduce

Well . I'm using default settings both app . And change background in Cmder Profile. Both are latest

### Actual Behavior

I get this strange color background
![proof](https://i.imgur.com/QKI5mb0.png)

**Comment by skyline75489** [comment]
I think this is #9693

**Comment by buinguyenhoangtho** [comment]
Thanks for helping guys. I'm fixed it. For anyone looking for resolutions. do it exactly in this link. It working. https://github.com/cmderdev/cmder/issues/2516#issuecomment-813459040

**Comment by buinguyenhoangtho** [comment]
Thanks for helping guys. I'm fixed it. For anyone looking for resolutions. do it exactly in this link. It working. https://github.com/cmderdev/cmder/issues/2516#issuecomment-813459040 . I will close it
