### ISSUE TITLE
The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

### ISSUE THREAD

**Issue by alancnet** [microsoft/terminal#9866]
### Windows Terminal version (or Windows build number)

10.0.19041.0 1.7.1033.0_x64

### Other Software

WSL 2
Ubuntu
Docker

### Steps to reproduce

1. Install Windows Terminal
2. Run Windows Terminal

### Expected Behavior

Windows Terminal should launch

### Actual Behavior

Windows terminal appears as a white window, and disappears. A dump file is created in C:\Users\alco\AppData\Local\CrashDumps

**Comment by alancnet** [comment]
This is what happens when I run Windows Terminal:

![White box](https://user-images.githubusercontent.com/2042102/115100338-cfc3fe00-9ef0-11eb-91aa-2afcd715b600.gif)

This is what it shows in the dump file:

![image](https://user-images.githubusercontent.com/2042102/115100372-ff730600-9ef0-11eb-9162-6962fae8f385.png)

**Comment by DHowett** [comment]
This is the same as /dup #9821. It looks like you’re running unpackaged due to the permissions on your WindowsApps directory ...
