### ISSUE TITLE
Feature Request: CMD's "start" command should open new tab instead of new window

### ISSUE THREAD

**Issue by rajan-31** [microsoft/terminal#9867]
# Description of the new feature/enhancement

> **Feature**: 
> 
> CMD's "start" command should open new tab instead of new window
> 
> OR
> 
> any other option to run command in separate tabs (like we open new tabs of specific terminal).

**Example**: 

`start npm run startMongo && start npm run local`

**Expected**: It should open two tabs of "Windows Terminal" running each command

**Current Behavior**: It opens two separate windows of CMD (also they are not Windows Terminal windows)

# Proposed technical implementation details (optional)

**Not sure about solution**

As per my knowledge currently it is not possible to open tabs with command in same instance, but like we can open new tabs of specific terminals using

`wt -p "Command Prompt" ; new-tab -p "Windows PowerShell"`

like this we can add new option to run the command in new tab.

Example: assume that the new option is "--run"

`wt --run "npm run startMongo" -p "Command Prompt" ; new-tab --run "npm run local" -p "Windows PowerShell"`

**Comment by LuanVSO** [comment]
try `wt --window 0  -p "Command Prompt" "npm run startMongo";  -p "Windows PowerShell" "npm run local"`

**Comment by rajan-31** [comment]
I got, 

[error 0x80070002 when launching `npm run startMongo']

[error 0x80070002 when launching `npm run local']

**Comment by zadjii-msft** [comment]
FYI when there's support for "setting the default terminal" (#492), then `start foo.exe` will open up `foo.exe` in a new WT tab. 

For now, you'll need to use the `wt -w` option. @rajan-31 out of curiousity, is your default profile a WSL profile? If you're trying to run a WSL commandline, you'll need to make sure to prefix the command with `wsl.exe -d {Whatever-Distro-You-Have-Installed}`, like `wt -w 0 -- wsl -d Ubuntu npm run startMongo`

/dup #492
/dup #4472
