### ISSUE TITLE
Unable to open new tab when the only open tab is settings

### ISSUE THREAD

**Issue by UmbralReaper** [microsoft/terminal#9868]
### Windows Terminal version (or Windows build number)

10.0.19042, 1.7.1033.0

### Other Software

None relevant.

### Steps to reproduce

1. Disable 'Always show tabs' (and relaunch if necessary).
2. Open a Settings tab using `ctrl+,` or the dropdown, it doesn't matter.
3. Close all other tabs.
4. Attempt to open a new tab using `ctrl+shift+1`, and find that it doesn't work.

### Expected Behavior

To be able to open a new tab.

### Actual Behavior

You are locked into the settings tab. Along with `ctrl+shift+1`, I tried `ctrl+shift+n`, `ctrl+shift+p`, and `ctrl+shift+t`. None work.

**Comment by skyline75489** [comment]
Yes this is a known issue. See #8767

**Comment by UmbralReaper** [comment]
And 8987 it seems. /dup #8767

**Comment by skyline75489** [comment]
Ha sorry the bot only listens to certain people that have the correct permission😅

I'll close it for you. Thanks for the feedback!

**Comment by UmbralReaper** [comment]
> Ha sorry the bot only listens to certain people that have the correct permission😅

I was afraid of that...
