### ISSUE TITLE
Very long `ToolTip`s get clipped 

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#9869]
The current directory of WSLv1 tab is `/mnt/c/Users/user/Downloads`, and the tooltip just reads `/mnt`. This is not useful since it's very generic, even `/mnt/c` would be more useful. Maybe even absence of this strange path would be less confusing.

![image](https://user-images.githubusercontent.com/1041752/115111283-e9f8ed00-9f7f-11eb-9e07-2fcdee3a33b3.png)

Terminal version: `Version: 1.7.1033.0`

**Comment by DHowett** [comment]
It just looks like it’s cut off (look at the part of the character to the right of `mnt`). We should probably fix that.

**Comment by vadimkantorov** [comment]
Maybe best to always put this path it on new line, then there wourld be at least 10-20 letters space. And then it could be ellipse'd...

**Comment by DHowett** [comment]
So, we don’t actually know that it’s a path. That’s the verbatim string that bash reported to us, with the username/hostname/path pre-formatted. Alas.

**Comment by vadimkantorov** [comment]
Summing up three other variants: 1) show PS1 on different line than OS name, 2) make tooltip radically larger, 3) have some heuristics for word-wrapping unknown PS1 (e.g. by slash or non-word characters)

**Comment by zadjii-msft** [comment]
Hmm, it looks like how we're building the tooltips doesn't account for the width of the text:

![image](https://user-images.githubusercontent.com/18356694/115227978-ceecc100-a0d6-11eb-995f-7d1b9180c868.png)


But then compare to:
```xaml
  <Button Content="Button with a simple ToolTip."
        ToolTipService.ToolTip="https://this.com/is/a/incredibly-long-hyperlink/that/might/have/too-long-a-tooltip"/>

```

![image](https://user-images.githubusercontent.com/18356694/115228839-dfea0200-a0d7-11eb-9313-f70fec00c8ae.png)

So `TabBase::_UpdateToolTip` and 
```xaml
    <Border x:Name="HyperlinkTooltipBorder"
            BorderBrush="Transparent">
        <ToolTipService.ToolTip>
            <ToolTip x:Name="LinkTip"
                     Placement="Mouse">
                <TextBlock IsTextSelectionEnabled="True">
                    <Run x:Name="HoveredUri" /> <LineBreak />
                    <Run x:Uid="HowToOpenRun"
                         FontStyle="Italic" />
                </TextBlock>
            </ToolTip>
        </ToolTipService.ToolTip>
    </Border>
```
in `termcontrol.xaml` will probably need to get updated.

**Comment by vadimkantorov** [comment]
Also, not sure why "ctrl+alt+2" shows up at a seemingly arbitrary margin (not left, not right, unclear the intent). With combination with a clipped tooltip, this looks also strange

**Comment by zadjii-msft** [comment]
The `ctrl+alt+2` is probably trying to center itself underneath the previous line of text. It just doesn't realize that it's container is _not_ as big as the text is 😉

**Comment by vadimkantorov** [comment]
My proposed tooltip (consistent captialization + PS1 on new line always + FS path wrapping heuristic for the first slash (so that for default Windows/Ubuntu PS1 scheme it looks okay in for short enough paths) + wrapping is prefixed by "... ":
```python
[Ctrl+Alt+2]: Ubuntu 18.04
vadimkantorov@DESKTOP-4UF8FID:
... /mnt/c/Users/user
.... more wrapping if needed
```

**Comment by Don-Vito** [comment]
As the one responsible for the mess, I can take a look later on.

**Comment by Don-Vito** [comment]
I will start with fixing the wrapping (one-liner). 
@zadjii-msft   - please let me know if you want to switch to another structure, like @vadimkantorov  suggested.

**Comment by zadjii-msft** [comment]
Nah, let's just fix the wrapping for now. That's easiest - everything else is just heuristics, which is a programmer word for "guessing" 😄 Plus, that doesn't involve any _real_ design changes, which would require a much lengthier discussion

**Comment by vadimkantorov** [comment]
Will this also fix `Ctrl` capitalization + shortcut placement?

**Comment by Don-Vito** [comment]
@vadimkantorov - no, I didn't fix any of those, sorry. 
* Regarding the shortcut placement, @zadjii-msft  - advised to leave it as is meanwhile
* Regarding the capitalization we need to do it.. but I guess it has larger scope that just a tool-tip, e.g., it might affect the command palette as well.

**Comment by Korb** [comment]
The tooltip for the new tab button is too short (or the text is too long) to understand what it says:
![2021-12-08_13-43-27](https://user-images.githubusercontent.com/3509797/145195569-25169c44-2bba-49e9-9fde-8f391b04d39c.png)

Related #5355 and #5484.
