### ISSUE TITLE
Unable to create new tabs or exit fullscreen mode in settings

### ISSUE THREAD

**Issue by joeyshi12** [microsoft/terminal#9874]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Steps to reproduce

1) Open the terminal and create a settings tab
2) Enter fullscreen and close whatever shell you are in with some shortcut (ctrl-shift-w)
3) Try creating new tabs using shortcuts or exiting fullscreen

### Actual Behavior

Using shortcuts like ctrl-shift-t to create new shell tabs no longer works and it is no longer possible to exit fullscreen using F11 or alt-enter. So, I can only close my current terminal and open a new instance at this point.

**Comment by Don-Vito** [comment]
@joeyshi12 - Unfortunately, this is a known issue widely discussed here: https://github.com/microsoft/terminal/issues/8767
