### ISSUE TITLE
Ask/warn on closing last tab of split pane

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#9876]
# Description of the new feature/enhancement

I have split-pane-mode with one tab per pane enabled. Closing one of the tabs (the last tab of a pane) closes the whole window.

Better would be to warn/ask the user.

Left pane | Right pane
------------ | -------------
one tab (powershell) | one tab (cmd)

# Proposed technical implementation details (optional)

On closing the last tab of a split pane the user should be asked what to do:
- Close pane.
- Close window.
- Cancel.

**Comment by Don-Vito** [comment]
@htcfreek - I guess there is some naming confusion:
* We have application Window
* One or more tab are displayed on the top of this Window (like in a browser)
* Each tab contains one or more panes
* Each pane contains a terminal

Given this terminology, is you ask is about "Prompt upon closing the last pane of the tab"?

**Comment by htcfreek** [comment]
@Don-Vito 
I agree to you that I misunderstand the UX hierarchy (window > tabs > panes).
But then for me the window was closed with two panes open in the last tab.

![wt-close-splitpane](https://user-images.githubusercontent.com/61519853/115156176-4b55b480-a083-11eb-8263-981a367b2e9a.gif)


1. There should be a warning that both panes are destroyed on closing the tab/window.
2. Maybe it's possible to make it more clear that there are more than one console open in this tab. (I have an idea and upload a mock up later.)

**Comment by Don-Vito** [comment]
@htcfreek  - Thanks for the screen capture! What you ask makes a lot of sense! I was asking about the terminology just to make sure if we such request exists already. Please see if https://github.com/microsoft/terminal/issues/5301 already addresses the same idea.

**Comment by htcfreek** [comment]
> @htcfreek - Thanks for the screen capture! What you ask makes a lot of sense! I was asking about the terminology just to check if we have such request already. Please see if #5301 already addresses the same idea.

Yes the issue addresses the same idea. I'll add a suggestion in the other issue.

Should I open a new issue for the suggestion of split-pane info and close my issue?

**Comment by Don-Vito** [comment]
I believe that you can repurpose this issue for adding panes info to the Tab title. I remember of seeing similar idea in some discussion but I cannot find it right now.

**Comment by htcfreek** [comment]
Closing as duplicate of #9883 and #5301.
