### ISSUE TITLE
Setting to start in split-pane-mode

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#9877]
# Description of the new feature/enhancement

Split-pane-mode is a great feature

Please add a setting to start wt in split-pane-mode. This would be great.

# Proposed technical implementation details (optional)

- Start mode (drop down): Single window|Split pane horizontal|Split pane vertical

- Split pane 1: `<profile selection drop down>`

- Split pane 2: `<profile selection drop down>`

**Comment by htcfreek** [comment]
> # Description of the new feature/enhancement
> 
> Split-pane-mode is a great feature
> 
> Please add a setting to start wt in split-pane-mode. This would be great.
> 
> # Proposed technical implementation details (optional)
> 
> - Start mode (drop down): Single window|Split pane horizontal|Split pane vertical
> 
> - Split pane 1: `<profile selection drop down>`
> 
> - Split pane 2: `<profile selection drop down>`
>

**Comment by Don-Vito** [comment]
So this seems as a variation of https://github.com/microsoft/terminal/issues/3586, which creates a pane with a profile selection.
Once we have such mode for panes we can use startupActions with something like:
```
new-tab --prompt-profile | split-pane -V --prompt-profile ; 
```

**Comment by htcfreek** [comment]
@Don-Vito 
I don't think of a profile selection. But yes, this can be a different possible choice. I think about a setting where the user can define specific profiles/tabs/panes to load on startup.

Something like `split-pane -V -profiles [powershell, cmd] | new-tab --prompt-profile`.

**Comment by Don-Vito** [comment]
Oh I see. Sorry for misreading the original ask.
So as we discussed in another thread, we already have the startupActions that already provide an option to run with different predefined tabs and panes.
What you are talking here is actually to create a nice UI in settings, that should allow us defining this behavior without editing the file. Right?

**Comment by htcfreek** [comment]
Yes. So this issue seems to be a duplicate of / to be related on #9878.

**Comment by Don-Vito** [comment]
Actually I am not from the team, just a contributor!
But I am sure @zadjii-msft will love to close it as duplicate :smile:

**Comment by zadjii-msft** [comment]
I love the smell of closing duplicates in the morning. Thanks all!

/dup #8802
/dup #756
