### ISSUE TITLE
Setting: Set mor than one profile as startup profile

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#9878]
# Description of the new feature/enhancement

Please add a feature to open wt with more than one tab. There should be a setting to enable this and a setting to configure the tabs/profile.

# Proposed technical implementation details (optional)

[X] Start wt with more tha one tab
[PowerShell; CMD] *

_*) This should be an input control. One entry (comma separated) per tab. The first entry is for the first and per default shown tab._

**Comment by Don-Vito** [comment]
@htcfreek - ["startupActions"](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#startup-actions) allow you to do this today. Unfortunately they are not exposed in the settings UI yet, but you can add them to the config file, e.g.,

```
"startupActions": "new-tab -p \"Git Bash\" --title Git --tabColor #641220; new-tab -p \"Windows PowerShell\" --title Posh --tabColor #15616d; focus-tab -n 0"
```

**Comment by htcfreek** [comment]
I think this should be added to settings ui for easier configuration.

**Comment by Don-Vito** [comment]
@htcfreek  - I absolutely agree. We even have a PR for it here: https://github.com/microsoft/terminal/pull/8812.
But it is blocked as we want to show more information about what will be executed, but it requires some additional refactor

**Comment by htcfreek** [comment]
@Don-Vito Feel free to close this as duplicate of #8802.

**Comment by zadjii-msft** [comment]
I love the smell of closing duplicates in the morning. Thanks all!

/dup #8802
/dup #756
