### ISSUE TITLE
Feature Request: Double Click Selection

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#988]
# Summary of the new feature/enhancement

Double-clicking the text buffer creates a selection encompassing the "word".
The delimiters for what makes a "word" are defined in the settings (described below).

Dragging after a double click maintains the "beginning of the word" anchor but changes the other one. 

**Settings**

| Property Name | Type | Description | Default Value |
| --------------- | ------- | ----------- | -------------- |
| "selectionDelimiters" | array | list of characters used as delimiters | `[' ', '/', '\']` |

Use case: easily select a path or word from the selection.

# Proposed technical implementation details (optional)
If possible, have XAML identify double-click. Everything else should be pretty straightforward. The TermControl will work with the Terminal to create the selection. When the event is triggered, we need to check the delimiters from the settings to decide what to select.

**Comment by mdtauk** [comment]
Would this support double clicking to select an entire word?  Or just double click to switch to mouse selection mode?

**Comment by carlos-zamora** [comment]
> Would this support double clicking to select an entire word? Or just double click to switch to mouse selection mode?

Assuming the window is focused and you're already in mouse selection mode, it should select the entire word (inclusive).

**Comment by mikepurvis** [comment]
Double click and drag is also important— like current PowerShell, it should be possible to select a line or word and then drag out to encompass more text.

**Comment by andb0t** [comment]
Wow, great job everyone! Could you let me know how I can find out when this change will actually be rolled out?

**Comment by carlos-zamora** [comment]
Since it’s merged to master, you can try it out by building the repo on GitHub today.

For the store update, it’ll be in the next release that’s being tracked with the [0.3 milestone](https://github.com/microsoft/terminal/milestone/10).

**Comment by Luuk34** [comment]
Double click does not work when clicking on the first character of a line
(tested in Version 0.3)
