### ISSUE TITLE
Expand/Unexpand split panel on shortcut

### ISSUE THREAD

**Issue by piradata** [microsoft/terminal#9880]
# Description of the new feature/enhancement

On 'terminator' terminal there is a shortcut that puts an splitted panel in "full-terminal-view", occupying all the space that was being used by the others split panels. This shortcut on terminator is 'Ctrl+Shift+X', pressed once, split goes full scren on corresponding tab, pressed again and split tab regains its former size.

This is useful when editing some file on vim or reading some output with less, so that we can concentrate on the text and after resize it to continue to do other things

# Proposed technical implementation details (optional)

When pressing some set shortcut, splitted tab goes full-screen, when pressed again it regains former size

**Comment by DHowett** [comment]
You can do this today with the [togglePaneZoom action](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#zoom-a-pane). You can bind it to whatever key you want, or you can access it with the command palette (Ctrl+shift+P)

**Comment by piradata** [comment]
Thanks!! Have missed this action on the docs!
Added the following in the config file and works pretty nice!

{
    "command": 
    {
        "action": "togglePaneZoom"
    },
    "keys": "alt+shift+x"
}
