### ISSUE TITLE
Adding pane info to tab title

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#9883]
The UX hierarchy is the following: window > tabs > panes

Maybe it's possible to make it more clear that there are more than one console open in this tab. 

![image](https://user-images.githubusercontent.com/61519853/115156384-4e9d7000-a084-11eb-8778-cfd6bbdde1a2.png)

_Originally posted by @htcfreek in https://github.com/microsoft/terminal/issues/9876#issuecomment-822036242_

**Comment by htcfreek** [comment]
@Don-Vito 
Do you search for issue #1147 as original issue for my idea.

**Comment by Don-Vito** [comment]
@htcfreek - actually I did, as I was quite sure I've seen this before, but wasn't able to find it! So probably this one also should be closed as duplicate.

**Comment by htcfreek** [comment]
> @htcfreek - actually I did, as I was quite sure I've seen this before, but wasn't able to find it! So probably this one also should be closed as duplicate.

@Don-Vito 
Feel free to do so.

**Comment by Don-Vito** [comment]
I cannot close anything - I am just a contributor, I can only submit PRs and some of them get accepted :smile:

**Comment by htcfreek** [comment]
Let's hold this issue open. Then the core team can deside to close and/or repost. 😅

**Comment by zadjii-msft** [comment]
I love the smell of closing duplicates in the morning. Thanks all!

/dup #1147
