### ISSUE TITLE
Dropdown next to new tab button uses wrong tooltip

### ISSUE THREAD

**Issue by BreeceW** [microsoft/terminal#9884]
### Windows Terminal version (or Windows build number)

1.8.1032.0

### Steps to reproduce

Hover over the chevron down icon in the tab strip and read the text.

### Expected Behavior

The tooltip should say something about the options contained in the dropdown.

### Actual Behavior

![More options dropdown tooltip as it is today reads ”Open a new tab“](https://user-images.githubusercontent.com/18747724/115160834-50f1d100-a068-11eb-88b6-0534efde174d.png)
The tooltip is the same on both the new tab button and the dropdown button. This is because the tooltip is [set](https://github.com/microsoft/terminal/blob/fb597ed304ec6eef245405c9652e9b8a029b821f/src/cascadia/TerminalApp/TabRowControl.xaml#L37) on the whole SplitButton control. I don’t believe there’s a way to set a different tooltip on the [PrimaryButton](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/SplitButton/SplitButton.xaml#L265) and the [SecondaryButton](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/SplitButton/SplitButton.xaml#L287), though I could be wrong. That said, SplitButton does not seem like the appropriate control for this use (it also sets the focused state on the new tab button when the flyout is open, which doesn’t make visual sense to me, but that could be a separate issue). The tooltip also claims that alt/shift clicking the dropdown button will perform some action, but that only works on the new tab button.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6078 for more discussion.

/dup #6078
/dup https://github.com/microsoft/microsoft-ui-xaml/issues/2064 (related)
