### ISSUE TITLE
Feature Request - Hotkey Toggle to Minimize/Maximize Terminal

### ISSUE THREAD

**Issue by animehunter123** [microsoft/terminal#9885]
Hello,

Thank you for the great work in wt! Appoligize if this has been mentioned before but:
![WT Photo](https://user-images.githubusercontent.com/42163211/115165477-06fcff80-a0e9-11eb-9c5a-7d689e9779f1.png)

Would it be possible to have a global hotkey toggle to minimize/maximize terminal to the system tray? For example, "MobaXterm" uses Ctrl+M to minimize and maximize globally as a hotkey. Can something similar be done for Microsoft Windows Terminal?

Attached is how it looks like in MobaXterm (just a example)

**Comment by skyline75489** [comment]
Hi! I think you're looking for #5727. This is unfortunely still a backlog item, which means there's currently no plan to implement it. 

You may also find #653 interesting.

/dup #5727

**Comment by zadjii-msft** [comment]
I wouldn't say _no_ plan  - there's definitely a plan (see #9274, #9854). "backlog" might not be entirely correct anymore 😋 

/dup #653
