### ISSUE TITLE
Clicking a tab triggers focus lose

### ISSUE THREAD

**Issue by TanukiSharp** [microsoft/terminal#9886]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

Use case 1

- Open a tab in Windows Terminal
- Ensure the shell has focus and caret allows typing in the shell
- Click the tab of the same pane
- Confirm the shell does not have focus anymore (cannot type)

Use case 2
- Open a tab in Windows Terminal
- Ensure the shell has focus and caret allows typing in the shell
- Focus any other application
- Give back focus to Windows Terminal by clicking a tab (not the shell part)
- Confirm the shell does not have focus anymore

That might be intended, but I think it's a bit of UX issue. Giving focus to rename textbox when double clicking a tab is of course necessary, but when simple clicking, I think the shell should get / keep focus.

Note that this does not happen when clicking a tab that is not active. When doing so, the shell correctly gets the focus.

Thanks.

### Expected Behavior

Shell get focus when click / tap the active tab.

### Actual Behavior

Shell loses focus when click / tap the active tab.

**Comment by vefatica** [comment]
I'm pretty sure that's a duplicate complaint and I wish it would be fixed.

IMO, if the double-click/rename mechanism is getting in the way, get rid of it.  There will still be right-click/rename.  That should be good enough.

**Comment by TanukiSharp** [comment]
I think double click to rename is legit, but there is no reason for simple click to grab the focus if nothing changes visually (appearance of a rename textbox or else).

I searched for duplicates before posting and couldn't find, but if you can, feel free to link the issue number here and I will close mine.

Thanks.

**Comment by zadjii-msft** [comment]
Sure is a duplicate.

/dup #3609
/dup #6680
