### ISSUE TITLE
Out-Gridview window launches behind instead of in foreground

### ISSUE THREAD

**Issue by campbellkerr** [microsoft/terminal#9888]
### Windows Terminal version (or Windows build number)

1.8.1032.0

### Steps to reproduce

Pipe something to out-gridview, eg

`ls | out-gridview`

### Expected Behavior

Gridview window should open in foreground (as it currently does in the ISE and powershell).

### Actual Behavior

Gridview window consistently opens in background (behind the Terminal window). Tested on 2 computers.

If you have Terminal maximised, the only way to tell that a Gridview window has been launched is that the PowerShell icon in the taskbar goes orange. The Gridview window also ends up at the bottom of the Alt+Tab order. I often use -passthru so this window behavior makes it more difficult.

![terminal-gridview](https://user-images.githubusercontent.com/38451588/115192238-e4410a00-a12d-11eb-9bf3-5df07cb5d026.gif)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #2988 for more discussion.

/dup #2988
