### ISSUE TITLE
Terminal window closes itself sometimes when losing focus

### ISSUE THREAD

**Issue by QAnders** [microsoft/terminal#9889]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

Leave the terminal open for some time

### Expected Behavior

The terminal shouldn't "self close"

### Actual Behavior

The terminal closes by itself sometimes, three-four times a day. If the Terminal is left open with a few tabs and loses focus it is sometimes closed (crashing?) by itself so when I go back to the Terminal it open anew and all open tabs are closed.

**Comment by zadjii-msft** [comment]
This sounds a _lot_ like you just got an update to the Terminal, and the Store force-closed the Terminal to install the update. The timing would line up with the most recent terminal update that got pushed out this week.

That being said, that shouldn't be happening 3-4 times _a day_. I wonder if a /feedback report right after this happens might have something we can go on? Maybe that'll help us track down the crashes.
