### ISSUE TITLE
Unable to type in Windows terminal

### ISSUE THREAD

**Issue by CorruptComputer** [microsoft/terminal#9890]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

PowerShell 7.1.3
Windows PowerShell 10.0.19042.928
Command Prompt 10.0.19042.928

### Steps to reproduce

- Open Windows terminal.
- Try to type.

### Expected Behavior

I should be able to type in the terminal.

### Actual Behavior

I am unable to type in the Terminal, tried with all three of the types listed above. 
Attached is a video of the issue, I am able to type in Powershell 7.1.3 but not when it is opened through Terminal.

https://user-images.githubusercontent.com/5573038/115236573-812d8400-a0e9-11eb-8f5b-754322a2b7ea.mp4

**Comment by CorruptComputer** [comment]
In the video, you can see the dots on the small white WhatPulse icon being the second from the left in the notification area of the taskbar. Each dot on the right side of that icon is a keypress, I am typing in the video even though it doesn't show anything in the Terminal.

**Comment by zadjii-msft** [comment]
(the following is copy-pasta, so yes I see that you've got the "Touch Keyboard and Handwriting Panel" started)

Can you confirm that the "Touch Keyboard and Handwriting Panel" service is running? You can check that with the command 

```sh
sc query TabletInputService
```

Which should get you something like:
![image](https://user-images.githubusercontent.com/18356694/97710878-55aad480-1a8a-11eb-9e93-bddadf6c4872.png)

If you're seeing that the service is running, could you check if `ctfmon.exe` is also running? Apparently `ctfmon.exe` is the _real_ important process, which the service is just used to resurrect. 

```
> tasklist /v /fi "imagename eq ctfmon.exe" /fo list

Image Name:   ctfmon.exe
PID:          10828
Session Name: Console
Session#:     1
Mem Usage:    26,536 K
Status:       Running
User Name:    REDMOND\migrie
CPU Time:     0:01:05
Window Title: N/A
```

![image](https://user-images.githubusercontent.com/18356694/98955703-d2937080-24c4-11eb-8daf-ae7b2efad705.png)

It needs to be running **with a stable PID**. So run that command a few times and make sure that the PID isn't changing.


Also, can you check `InputServiceEnabled` in the registry? You can do that with:

```
reg query hklm\software\microsoft\input /v InputServiceEnabled
```

Which should give you something like:
```
HKEY_LOCAL_MACHINE\software\microsoft\input
InputServiceEnabled REG_DWORD 0x1
```

(See #8045, #4448)

**Comment by CorruptComputer** [comment]
Here are the outputs from those commands:

```PowerShell
PS C:\Users\ngupton> sc query TabletInputService
SERVICE_NAME: TabletInputService
        TYPE               : 30  WIN32
        STATE              : 4  RUNNING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

PS C:\Users\ngupton> tasklist /v /fi "imagename eq ctfmon.exe" /fo list
INFO: No tasks are running which match the specified criteria.

PS C:\Users\ngupton> reg query hklm\software\microsoft\input /v InputServiceEnabled
HKEY_LOCAL_MACHINE\software\microsoft\input
    InputServiceEnabled    REG_DWORD    0x1
```

It looks like ctfmon.exe is not running for some reason, strange. I tried to start it, but it looks like it might be closing or crashing right after launch.
```PowerShell
PS C:\Users\ngupton> ctfmon.exe
PS C:\Users\ngupton> tasklist /v /fi "imagename eq ctfmon.exe" /fo list
INFO: No tasks are running which match the specified criteria.
```

**Comment by zadjii-msft** [comment]
@ebadger can you help OP here figure out why `ctfmon.exe` is crashing on launch?

**Comment by ebadger** [comment]
> Here are the outputs from those commands:
> 
> ```powershell
> PS C:\Users\ngupton> sc query TabletInputService
> SERVICE_NAME: TabletInputService
>         TYPE               : 30  WIN32
>         STATE              : 4  RUNNING
>                                 (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
>         WIN32_EXIT_CODE    : 0  (0x0)
>         SERVICE_EXIT_CODE  : 0  (0x0)
>         CHECKPOINT         : 0x0
>         WAIT_HINT          : 0x0
> 
> PS C:\Users\ngupton> tasklist /v /fi "imagename eq ctfmon.exe" /fo list
> INFO: No tasks are running which match the specified criteria.
> 
> PS C:\Users\ngupton> reg query hklm\software\microsoft\input /v InputServiceEnabled
> HKEY_LOCAL_MACHINE\software\microsoft\input
>     InputServiceEnabled    REG_DWORD    0x1
> ```
> 
> It looks like ctfmon.exe is not running for some reason, strange. I tried to start it, but it looks like it might be closing or crashing right after launch.
> 
> ```powershell
> PS C:\Users\ngupton> ctfmon.exe
> PS C:\Users\ngupton> tasklist /v /fi "imagename eq ctfmon.exe" /fo list
> INFO: No tasks are running which match the specified criteria.
> ```

Could you try following these instructions:
https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

and enable collecting user mode dumps to your local disk?

Do you see any ctfmon dumps?  If so, I'd like to see one of them.

Thanks,

Eric

**Comment by ebadger** [comment]
> Hey @ebadger I enabled the dumps in my registry, but running `ctfmon.exe` doesn't seem to produce any.
> The `%LOCALAPPDATA%\CrashDumps` folder is empty after running these commands:
> 
> ```powershell
> PS C:\Users\ngupton> ctfmon.exe
> PS C:\Users\ngupton> tasklist /v /fi "imagename eq ctfmon.exe" /fo list
> INFO: No tasks are running which match the specified criteria.
> ```

Would you run this command and reply with output:
tasklist /m msctfmonitor.dll

**Comment by ebadger** [comment]
> Sure, no problem. Here it is:
> 
> ```powershell
> PS C:\Users\ngupton> tasklist /m msctfmonitor.dll
> 
> Image Name                     PID Modules
> ========================= ======== ============================================
> taskhostw.exe                12000 MsCtfMonitor.dll
> ```

please try terminating PID 12000, signing out, and signing back in

**Comment by CorruptComputer** [comment]
That seems to have fixed it, I'm able to type now, what a strange issue...

Thanks for your help!

**Comment by zadjii-msft** [comment]
holy crap, @ebadger you're a wizard. Thanks!
