### ISSUE TITLE
Allow choosing the language for the UI

### ISSUE THREAD

**Issue by sboukortt** [microsoft/terminal#9892]
# Allow choosing the language for the UI

I have noticed that “Settings” now shows a GUI by default instead of the JSON file directly. This is quite convenient, however it displays what looks like an automatic translation into my system language (French), with for example “focus” being translated as “mise au point”, as in “adjustment (of camera focus)”, and so the UI is very hard to understand. It’s also inconsistent, with some verbs in the infinite form (as they usually are in other UIs) and some in the imperative.

Until such issues are fixed, it would be nice if I could simply use the original English UI without having to change the language system-wide. It would be far easier than trying to guess what the original text was.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5497 for more discussion.

/dup #5497
