### ISSUE TITLE
Shift-uppercase won't work if switch language on terminal page

### ISSUE THREAD

**Issue by hamid7621** [microsoft/terminal#9894]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Steps to reproduce

1 -> Open Terminal in different  language ( mine was Persian )
2 -> Switch language to English
3 -> Hold " Shift " to input upper case letter 
Nothing happens 

### Actual Behavior

Shift -upper case should be working in every situations

**Comment by zadjii-msft** [comment]
Out of curiosity, are you using `ssh`? What shell program are you using (`cmd`, `powershell`, `bash`, etc)?

**Comment by hamid7621** [comment]
No I was on my local . I am using `powershell`

**Comment by n-zhi** [comment]
I have the same problem in PowerShell-type tabs. And this problem is persistent between windows installs. My locales are Russian and English.

**Comment by zadjii-msft** [comment]
Okay, so this is bizarre. We've seen this intermittently before, over in #7087 and #8450. From that thread: https://github.com/microsoft/terminal/issues/7087#issuecomment-676782357

> Found a fix. If you have the same problem as me, then updating PSReadLine to the latest preview version can help you. Check out this [PowerShell/PowerShell#10794](https://github.com/PowerShell/PowerShell/issues/10794) and this [PowerShell/PSReadLine](https://github.com/PowerShell/PSReadLine) for more information.

@hamid7621 Could you try that, and see if that resolves the issue?

**Comment by hamid7621** [comment]
Thanks @zadjii-msft , it was helpful and issue resolved by  upgrading the module .
