### ISSUE TITLE
Mouse input support for vim in Windows Terminal

### ISSUE THREAD

**Issue by MhammadDayeh** [microsoft/terminal#9896]
In Linux and macOS, I can use my mouse with vim when I do 'set mouse=a', I can scroll thru the opened file, select text, click etc.
I would like to make this happen in Windows Terminal because sometimes it is useful to use the mouse, even when I'm used to keyboard shortcuts. I know that mouse support is added to Windows Terminal to be used in WSL, but its good to have it for other uses.

This video shows that I cannot use my mouse to navigate the app.
V
https://user-images.githubusercontent.com/42265793/115291009-479a5e80-a165-11eb-9ca4-1c65fe692e88.mp4

This video shows how I am supposed to be able to use the app, I can click, move, scroll and use the mouse.
V
https://user-images.githubusercontent.com/42265793/115290971-3bae9c80-a165-11eb-853e-47a664ba2661.mp4

Is it possible to make Windows Terminal recognize mouse input and use it like WSL? Thank you.

**Comment by skyline75489** [comment]
I think this is #376. Unfortunely mouse input support does not for vim atm . If you really want to use that, you can try neovim, which uses VT mouse input.

**Comment by zadjii-msft** [comment]
Yep, sure is.

/dup #376

**Comment by MhammadDayeh** [comment]
Thank you @skyline75489 @zadjii-msft.

**Comment by ch2925** [comment]
I'm using vim under cygwin with python 3.8.The mouse input works well with it.

**Comment by MhammadDayeh** [comment]
Thank you @ch2925, I am familiar with cygwin and wanted to try it out since long ago, ill c.
