### ISSUE TITLE
Cursor positioning bug when entered text overflows to next line on bottom of the window

### ISSUE THREAD

**Issue by JakaBac** [microsoft/terminal#9897]
Terminal app 1.7.1033.0 has an issue redrawing/positioning cursor when the cursor is positioned in the middle of the line and the window is resized horizontally so the gets broken onto the new line while everything scrolls up.

Steps to reproduce:
1. Open Terminal (PowerShell)
2. Push Enter enough times to get to the bottom of the window
3. Enter line long enough so it will get broken when window is resized horizontally
4. Move cursor backwards and enter a different character to mark your position
5. Resize the window horizontally.
6. When the line gets broken and text scrolls up observe that the cursor is not where it should be

Old console doesn't have this issue.

cmd.exe in Terminal app has a similar issue

**Comment by DHowett** [comment]
This doesn't seem to be different from #6546.

**Comment by JakaBac** [comment]
Probably this is the same issue. But I can always reliably reproduce it.

**Comment by DHowett** [comment]
This is really helpful -- I bet that we could use it to write a repro case. Thanks! :smile:

**Comment by JakaBac** [comment]
It is easiest to reproduce with PowerShell, since there the cursor really jumps someplace unexpected. With cmd.exe and WSL (Ubuntu) it takes little bit more resizing back and forth. The cursor stays where it should, but the text buffer gets messed up

**Comment by zadjii-msft** [comment]
Thanks for the consistent repro steps! I'll move thee discussion over to #6546 

/dup #6546
