### ISSUE TITLE
Multi-cursor: Keyboard inputs across multiple panes

### ISSUE THREAD

**Issue by dark-swordsman** [microsoft/terminal#9899]
# Description of the new feature/enhancement

The ability to type into one pane and have that input sent to all panes, or to have the executed command on one pane be sent to all panes.

This feature exists on OSX's native terminal as multi-cursor, as well as in Mobaxterm as "Multi-exec". Though, the implementation on OSX allows you to toggle on or off with existing panes, where Mobaxterm requires you to re-configure the panes every time you open multi-execute.

An example of the benefit for this feature is if you are configuring two or more machines to do the same thing. It is useful when you are debugging and testing something, where a docker container or something similar may be too much effort for just testing.

So for example, say that I am running 6 VMs on a machine for game servers (let's say Counter Strike). It turns out that one or two lines in a configuration file need to be changed, and the changes would be done identically on all machines. 

With multi-cursor, I would be able to make the change at the same time on all machines, save, and then reboot the VMs at the same time. This is in a scenario where docker containers are more effort than would be a benefit, especially when an image can be created locally on a VM host and spawned to other machines. But in this case, multi-cursor would come at a great benefit where time is sensitive.

As another note, I would add that you would be able to create multiple panes and then go to the same directory in each, though that matters more when each pane is on a different server. If on the same machine, then #3158 would basically solve that problem.

**Comment by zadjii-msft** [comment]
Sounds like what you're describing is "Broadcast input mode", something we're tracking in #2634, that we've got a spec for in #9365, and we have a draft implementation in #9222.

/dup #2634

**Comment by iDevGIS** [comment]
Yep!
