### ISSUE TITLE
Windows Terminal 版本: 1.7.1033.0

### ISSUE THREAD

**Issue by lvzhuangzhuang** [microsoft/terminal#9901]
新的版本打开后窗口总是在最前面，处于置顶状态只能通过最小化窗口来隐藏，而不能像其他窗口一样在使去焦点后放隐藏

**Comment by skyline75489** [comment]
Translation: the new version will always be topmost window after launching. You can only hide the window by minimizing, instead of moving focus off it.

**Comment by zadjii-msft** [comment]
Do you have `"alwaysOnTop": true` in your settings? If so, remove that setting.

If that doesn't work, does <kbd>ctrl+shift+p</kbd> (to open the command palette), then choosing the option "toggle always on top mode" (no idea what that would translated to 😕), fix it?
