### ISSUE TITLE
Title/Tab Bar Disappears

### ISSUE THREAD

**Issue by slin08** [microsoft/terminal#9904]
I am new users to Windows Terminal. The first day it worked as I like. Then the next day I hit this problem.  The window has no title bar. The first line of the text is at the first row of the display. See the screen print below. 
I hope there is just some setup issue.  Can anyone give some advice? 
Thanks!

![screenprint](https://user-images.githubusercontent.com/48886751/115414445-0ab18480-a1c4-11eb-9890-567b4e35cdcf.png)

**Comment by DHowett** [comment]
Did you press F11 or Alt+Enter to enter full-screen mode? Can you try to press F11 or Alt+Enter to exit full-screen mode?

**Comment by slin08** [comment]
👍😊
Yes. that solved the problem.
