### ISSUE TITLE
Have the same problem

### ISSUE THREAD

**Issue by BertasCZ** [microsoft/terminal#9908]
Have the same problem

Txt2AL version 14.0.41862.0 and 14.0.45012.0 both fail 

Example on delta that fails

OBJECT Modification "General Ledger Setup"(Table 98)
{
  OBJECT-PROPERTIES
  {
    Date=20180919D;
    Time=130000T;
    Version List=NAVW113.00,PF1.01;
  }
  PROPERTIES
  {
    Target="General Ledger Setup"(Table 98);
  }
  CHANGES
  {
    { Insertion         ;Documentation=BEGIN
                                         PF1.00 PKR 29.06.2018 Added fields 50000..50005.
                                       END;
                                        }
    { Insertion         ;InsertAfter="Show Amounts"(Field 164);
                         ChangedElements=FieldCollection
                         {
                           { 50000;  ;From Salary Dimension Code;Code20  ;TableRelation=Dimension;
                                                                          CaptionML=[DAN=Fra dimensionskode l›n;
                                                                                     ENU=From Salary Dimension Code] }
                           { 50001;  ;From Salary Dim. Value Filter;Code50;
                                                                          TableRelation="Dimension Value"."Consolidation Code" WHERE ("Dimension Code"=FIELD("From Salary Dimension Code"),
                                                                                                                                      "Dimension Value Type"=CONST(Standard));
                                                                          ValidateTableRelation=false;
                                                                          TestTableRelation=false;
                                                                          CaptionML=[DAN=Fra dim.v‘rdifilter l›n;
                                                                                     ENU=From Salary Dim. Value Filter] }
                           { 50002;  ;To Salary Dimension Code;Code20    ;TableRelation=Dimension;
                                                                          CaptionML=[DAN=Til dimensionskode l›n;
                                                                                     ENU=To Salary Dimension Code] }
                           { 50003;  ;To Salary Dim. Value Filter;Code50 ;TableRelation="Dimension Value"."Consolidation Code" WHERE ("Dimension Code"=FIELD("To Salary Dimension Code"),
                                                                                                                                      "Dimension Value Type"=CONST(Standard));
                                                                          ValidateTableRelation=false;
                                                                          TestTableRelation=false;
                                                                          CaptionML=[DAN=Til dim.v‘rdifilter l›n;
                                                                                     ENU=From Salary Dim. Value Filter] }
                           { 50004;  ;Default Dimension Code;Code20      ;TableRelation=Dimension;
                                                                          CaptionML=[DAN=Standard dimensionskode;
                                                                                     ENU=Default Dimension Code] }
                           { 50005;  ;Default Dimension Value Code;Code20;TableRelation="Dimension Value".Code WHERE ("Dimension Code"=FIELD("Default Dimension Code"),
                                                                                                                      "Dimension Value Type"=CONST(Standard));
                                                                          CaptionML=[DAN=Std. dimensionsv‘rdikode;
                                                                                     ENU=Default Dimension Value Code] }
                         }
                          }
    { PropertyModification;
                         Property=Version List;
                         OriginalValue=NAVW114.01;
                         ModifiedValue=NAVW113.00,PF1.01 }
  }
  CODE
  {

    BEGIN
    END.
  }
}

_Originally posted by @slnbornerup in https://github.com/microsoft/AL/issues/5598#issuecomment-720968467_

**Comment by zadjii-msft** [comment]
What now? How is this a Terminal bug?
