### ISSUE TITLE
When Right Clicking to another folder or directory, it should add as a new tab not as a new window.

### ISSUE THREAD

**Issue by BroJenuel** [microsoft/terminal#9912]
So I have a terminal opened, now I wanted to open the terminal a new terminal in a new directory by right-clicking and selecting `open in windows terminal`.

Current behavior:
When I open a new directory and `right-click` to it, and select `open in windows terminal` it basically opens a new terminal in a ***new window***.

Proposed behavior:
If I open a new directory and `right-click` to it, and select `open in windows terminal`, it should open it in a ***new tab***.

**Comment by skyline75489** [comment]
Is this covered by #4472 ? I'm not really sure.

**Comment by BroJenuel** [comment]
it seems i did not the answer on the issue you send... by the way I am using the latest stable version

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7071 for more discussion.

/dup #7071
