### ISSUE TITLE
Implement some sort of ssh client into terminal

### ISSUE THREAD

**Issue by rhsCZ** [microsoft/terminal#9917]
# Description of the new feature/enhancement
It should be nice to have some ssh client implemented into terminal Instead of having to opened another program when working with VPS or something remotly. I think it's good idea. Instead of opening program like putty you will just open new tab and you're ready(almost). IP and port should be set in profiles. And this ssh client should have support for auto-logging via private key at least.

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
OpenSSH comes with windows. You can set up a profile that runs `ssh.exe` today!
