### ISSUE TITLE
Moving tabs to any order

### ISSUE THREAD

**Issue by rhsCZ** [microsoft/terminal#9918]
# Description of the new feature/enhancement
I can't move opened tabs by mouse to order them as i like to be(only way is open them in order i want to have them opened). it would be nice to implement some of moving tabs(like drag&drop, similar to Mozilla Firefox browser) to order them and create new terminal when tab is moved away of terminal window and split back if exactly one tab is opened in terminal and i have opened another with multiple tabs to be able to join these tabs to split into one window.

# Proposed technical implementation details (optional)

**Comment by skyline75489** [comment]
Is #1256 what you looking for?

**Comment by rhsCZ** [comment]
Ah yes. when i was searching i could't find anything(maybe baucause of different namings)
