### ISSUE TITLE
SettingsUI: keep "page" when changing profile

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#9920]
# Description of the new feature/enhancement

I have seven profiles.  Yesterday I was leisurely switching among them in the SettingsUI, essentially comparing them.  It would have been a better experience if the UI stayed on the same "page" ("General", "Appearance", "Advanced") when I switched profiles instead of automatically going to "General".

**Comment by zadjii-msft** [comment]
So for the record, I experimented with this before!

https://github.com/microsoft/terminal/pull/8844#issuecomment-764925226

> > should going back to "Windows PowerShell" have Appearance selected?
> 
> So, I had it that way in [67e38a3](https://github.com/microsoft/terminal/commit/67e38a307cb5917a3644c38045ede40e1188c6a3), but that actually felt weird. Idk, it was definitely a subjective choice, but it _felt_ like changing profiles should return to the general pivot. Reverting that would be easy. It would I guess also fix the "rename profile returns to the general pivot" problem

idk, I'm conflicted on this. It felt weird before, but it seems like it makes sense on paper. I'll leave it for the team to discuss. The fix is trivial.

\<discussion>

**Comment by vefatica** [comment]
In my case, I wanted to compare the appearances of various profiles.  Moving around among the profiles took twice the mouse clicks.  Starting at "General" is arbitrary (might as well start elsewhere) and doesn't seem to serve any purpose.

**Comment by zadjii-msft** [comment]
Team consensus: lets do it.

**Comment by vefatica** [comment]
Suits me.  Watch all the complaints.  😁

**Comment by DHowett** [comment]
> Team consensus: lets do it.

> Suits me. Watch all the complaints. 😁

Sorry? "Let's do it" is common parlance for "let us implement the thing that has been requested"...

**Comment by vefatica** [comment]
I figured that.  What's your point?  Was I wrong to close the issue?

**Comment by DHowett** [comment]
Yeah! We're gonna use this issue to track completing the work to make the profiles page remember where it was. Why'd you close it? :smile:

**Comment by vefatica** [comment]
I figured a decision was the end.  You don't always use an original suggestion to do the tracking, do you?

**Comment by zadjii-msft** [comment]
> You don't always use an original suggestion to do the tracking, do you?

Not always, but like 99.97% of the time we do. We usually only file our own versions for follow-ups. Like, #653 is the thread tracking adding support for quake mode, but #8888 is the thread for "everything related to quake mode after the initial PR". The only exceptions I can think of are #1564 and #5000

**Comment by DHowett** [comment]
AHH! I understand. Sorry! Yeah, Mike's got it here. We love to use the original issue since it lets the suggester know how we're doing, too. :smile:

**Comment by vefatica** [comment]
Then what ... someone comes back here, notes that it has been implemented, and closes it?  I don't see a lot of that but I admit that I'm not paying close attention to many issues.

**Comment by DHowett** [comment]
So, we use these issues (user suggestions, user bug reports, user requests even) as the currency of work tracking in our project. We talk about them all the time -- "let's fix 376" or "9920 is a good idea, let's do it" and then use that issue _mostly_ for the lifetime of the request.

We mention it in any pull request, too:

* "Closes #XXXX" or "Fixes #XXXX" are two keywords GitHub picks up to automatically close the related bug when the pull request merges
* "Related to #XXXX" adds a link between the bug and the PR so somebody who's interested in how the work is going can follow it.

Once the feature is complete and _released_, the commit and the changelog entry mentions the pull request number. Our release bot finds all issues "Closed" or "Fixed" by any PR mentioned in the changelog, and tells the original submitter that their submitted issue, request, etc. was addressed in whatever version mentioned it.

**Comment by DHowett** [comment]
I realize that I set a bad precedent with your issues specifically. I've closed them early when I did not agree with them, only to come back and fix the issue anyway. That makes it look like we track the work elsewhere . . . and I'm sorry about that! :smile:

**Comment by vefatica** [comment]
OK, that sounds vaguely familiar.  Thanks for the explanation.
