### ISSUE TITLE
New Release old problems.

### ISSUE THREAD

**Issue by 237dmitry** [microsoft/terminal#9921]
New version, old problems. When will you finally make mouse support available in third-party apps? When will there be a normal copy-paste in the editors? You are engaged in decorating when the BASIC functions are not implemented.

Why are you like this?

**Comment by DHowett** [comment]
1. #376 (mouse support in Windows applications.)
2. You can configure copy/paste however you want
3. There is no need for you to be unkind. Please follow the community guidelines when submitting issues.
