### ISSUE TITLE
Add ctrl+T to stop current task

### ISSUE THREAD

**Issue by josh-65** [microsoft/terminal#9923]
# Description of the new feature/enhancement
Adding this would act like crtl+c on the cmd. currently it used for copying so ctrl+T should be used as it common for other program's and is not used.

**Comment by DHowett** [comment]
You can safely bind ^T to send the same signal as ^C in your settings file.

In the keybindings section:

```
{ "command": { "action": "sendInput", "input": "\u0003" }, "keys": "ctrl+t" },
```

:smile:
