### ISSUE TITLE
Parsing "-d" argument has minor issues

### ISSUE THREAD

**Issue by tavrez** [microsoft/terminal#9927]
Greeting,
I want to have something like this in registry for some operations:
```cmd
wt -d "%V"
```
**a small note about `%V`:** for folders when it's resolved it has no `\` at the end but for root drives it has(`c:\` vs `c:\folder`).
So the command is going to be in one of these forms:
```cmd
wt -d "C:\folder"
wt -d "C:\"
```
First line is fine, however, second line will instantly crash.
The problem with it is the `\"`, which is parsed like `"`, if I do one of these:
```cmd
wt -d "c:\\"
wt -d "c:"
wt -d c:\
wt -d c:
```
Everything become perfect, however, this is not something `%V` is going to be resolved into.
I also cannot use `wt -d %V`(without quotes) in registry, because it makes trouble for folders with space.

**Comment by zadjii-msft** [comment]
Thanks for reporting this! I think we've got another thread tracking the same underlying issue here. From that thread:

> As a quick hack for %V, you might be able to use.. hmm. `"%V\."`?

/dup #4571
