### ISSUE TITLE
Numbering the tab.

### ISSUE THREAD

**Issue by SuJiKiNen** [microsoft/terminal#9929]
# Description of the new feature/enhancement
similar to this question
https://askubuntu.com/questions/839617/gnome-terminal-title-as-number-position-of-the-tab

this would make switching faster.

# Proposed technical implementation details (optional)
may related to Spec: #2080, #7240
environment variable expand in title

so our title would be the title of title
like `${icon} ${number} ${origin_title}'`
this makes title more flexible

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1320 for more discussion.

/dup #1320
