### ISSUE TITLE
Add a shortcut for Close Pane

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#993]
Right now the user needs to manually `exit` the pane.

**Comment by varemenos** [comment]
Doesn't that already happen with Ctrl + W?

**Comment by zadjii-msft** [comment]
@varemenos Panes and Tabs are not the same thing. Tabs are the top-level entity, that may host many panes. When you open a new tab, it has one pane in it by default. This pane can be split into many panes that all occupy the same tab. Take a look at [this spec](https://github.com/microsoft/terminal/blob/master/doc/cascadia/Panes.md) for more details.

**Comment by DHowett-MSFT** [comment]
Idea: Let's make Ctrl+W "ClosePane" by default, and closing the last pane closes the tab. Include  a possibly-unbound-by-default "CloseTab". :smile:

**Comment by zadjii-msft** [comment]
> Idea: Let's make Ctrl+W "ClosePane" by default, and closing the last pane closes the tab. Include a possibly-unbound-by-default "CloseTab". 😄

I like this idea SO MUCH that I'm going to do it next in my list of panes work.
