### ISSUE TITLE
cyrillic support for terminal 

### ISSUE THREAD

**Issue by dobrys** [microsoft/terminal#9931]
Cyrillic text displayed as ????
### ### ![image](https://user-images.githubusercontent.com/839961/115867303-99800480-a443-11eb-9aab-b31326f6deee.png)

Windows Terminal
Version: 1.7.1091.0

Windows 10 Pro 20H2
os build : 19042.928
Windows Feature Experience Pack 120.2212.551.0

**Comment by zadjii-msft** [comment]
You should check out #4982. Looks like PowerShell 5.x ("Windows PowerShell") doesn't support unicode particularly well, but PowerShell 7.+ does.


/dup #4982
