### ISSUE TITLE
Remove Old Powershell from Dropdown List.

### ISSUE THREAD

**Issue by Xioto** [microsoft/terminal#9934]
I am trying to remove the Old Powershell from the Dropdown List, but when I do and click "Save", It just switches it back and does not remove it. How do I fix this? 

I do also have Powershell 7.
I am on Terminal V 1.7.1033.0
I am on Dev Build 21364.1

**Comment by DHowett** [comment]
What is "PowerShell V1"? We do not have a V1 of powershell...

**Comment by skyline75489** [comment]
Wild guess: V1 = Windows PowerShell

**Comment by nonspin** [comment]
You can at least hide it with the "Hide profile from dropdown"-toggle (using the settings ui)
or adding -> hidden: true 
to "Windows Powershell" in your settings.json
Removing/Deleting it is not possible because it's a Default Profile

**Comment by Xioto** [comment]
Very sorry, I have no idea what I meant by V1, I mean the powershell that is located here : %SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe

@nonspin  When I try and hide it, it just changes it back and re appears.

**Comment by Xioto** [comment]
![image](https://user-images.githubusercontent.com/72493732/115958116-f93ae600-a4fd-11eb-84f3-ba44bc3dc849.png)

**Comment by j4james** [comment]
I recently had a similar problem when installing Terminal Preview (v 1.8.1032.0) on a new machine. I tried to hide the _Azure Cloud Shell_ profile via the settings UI, but as soon as I saved the settings the radio button was turned off again. The problem went away after closing and reopening the terminal (I might have made other settings changes inbetween, so I'm not certain that reopening the terminal was all that was necessary to fix it).

**Comment by skyline75489** [comment]
Funny that,I think I also hit this once and forgot how I managed to figure it out. Probably the same as James did.

**Comment by Xioto** [comment]
Sorry, I tried James' solution, but it did not work. :(

**Comment by zadjii-msft** [comment]
@Xioto can you share your `settings.json`? I've got a theory about (#9855, #9864, #9938) that more data might help put together. Either it's all the same issue:
* Some of our controls (especially toggle buttons) don't necessarily work to edit layered profiles. Maybe the two way bindings are broken?

Or there's two separate problems:
* Sometimes the radio buttons don't actually change the settings model
* Something is weird about layered profiles

**Comment by Xioto** [comment]
I will add my settings.json when I get back homr, I have also tried changing the setting in the json file, but it switches back automatically just like the GUI

**Comment by Xioto** [comment]
So here is my `settings.json`.  https://pastebin.com/LLnF04X9

I had to remove some Profiles as they included Personal Info. 
If you need any more help or info, just ask.
Hope this helps!

**Comment by Xioto** [comment]
So here is my `settings.json`.  https://pastebin.com/LLnF04X9
For some reason Powershell 7 does not show as its own Profile, but it shares a profile with the old Powershell. ¯\_(ツ)_/¯

I had to remove some Profiles as they included Personal Info. 
If you need any more help or info, just ask.
Hope this helps!

**Comment by zadjii-msft** [comment]
We've managed to track down a minimal repro of this. We're now tracking this in #9962. Thanks for the help!

/dup #9962
