### ISSUE TITLE
ctrl+alt+<num> behaves differently from altGr+<num>

### ISSUE THREAD

**Issue by KnoxZZ** [microsoft/terminal#9936]
# Description
I can't insert special characters such as `@` with `ctrl+alt+2`, using `altGr+2` works normally.
The only combinations that work are `ctrl+alt+0` and `ctrl+alt+?`. I found [this issue](https://github.com/microsoft/terminal/issues/3079) concerning the latter one. 

# Steps to reproduce

1. Use ISO Nordic layout
2. Open Windows Terminal
3. Press `ctrl+alt+2`

## Expected behaviour

Inputs `@` to terminal

## Actual behaviour

Inputs nothing to terminal

# Environment
```
Microsoft Windows [Version 10.0.19042.928]
Windows Terminal: Version: 1.7.1033.0
Keyboard Layout:  ISO Nordic
```

**Comment by Teiem** [comment]
Hey, I have the same problem, how did you fix it?

**Comment by dosshell** [comment]
@Teiem : To solve this you can disable the terminal shortcuts. Modify your `settings.json` such that the action array contains the following:
```
"actions":
[
    { "command": null, "keys": "ctrl+alt+1" },
    { "command": null, "keys": "ctrl+alt+2" },
    { "command": null, "keys": "ctrl+alt+3" },
    { "command": null, "keys": "ctrl+alt+4" },
    { "command": null, "keys": "ctrl+alt+5" },
    { "command": null, "keys": "ctrl+alt+6" },
    { "command": null, "keys": "ctrl+alt+7" },
    { "command": null, "keys": "ctrl+alt+8" },
    { "command": null, "keys": "ctrl+alt+9" }
]
```
