### ISSUE TITLE
No APT scrollback history while connected to Ubuntu via SSH

### ISSUE THREAD

**Issue by dmilojevic** [microsoft/terminal#9939]
### Windows Terminal version
Stable: v1.7.1901
Preview: v1.8.1032
(Same behavior on a few previous versions that I tested)

### Windows OS version
Windows 10 - Builds 20H2 and 2004

### Other software
OpenSSH: version originally packed within Windows Optional updates, version from Powershell github, and Cygwin version 8.5p1.

**Steps to reproduce / Actual behavior**

    When connected to a remote Ubuntu server, if APT produces multiple pages of text,
    there's nothing in the scrollback of the Windows Terminal. When connected to other
    Linux headless hosts, also Debian derivatives (Armbian, Raspberry OS), all lines
    generated by APT end up in scrollback. If Command Prompt is used instead of
    Windows Terminal, even on Ubuntu server APT fills the scrollback.

**Expected Behavior**

    Windows Terminal should have all the lines generated by APT in its scrollback.

**Comment by skyline75489** [comment]
Just to make sure, `APT` is the `Advanced Packaging Tool` , right? The one can install packages.

**Comment by dmilojevic** [comment]
Hi. Yes. The built-in apt-get tool for software packages management.

**Comment by skyline75489** [comment]
Can you perhaps add a screenshot showing the correct vs incorrect behaviour? I don't honestly understand how the expected scrollback is, based on my limited experience with APT.

**Comment by zadjii-msft** [comment]
This is actually something we're already tracking: /dup #3673
