### ISSUE TITLE
Paste using Windows Clipboard doesn't work if ctrl+v unbound

### ISSUE THREAD

**Issue by rnbdc** [microsoft/terminal#9942]
If I try to use Windows Clipboard manager to paste text into Windows Terminal 1.7.1033.0 I can't do it if I { "command": "unbound", "keys": "ctrl+v" }

I need to unbound crtl+v because I need ctrl+v in some shell programs. Paste works fine with crtl-shift-v, but not with Windows Clipboard manager, which then inserts inserts a literal ctrl-v instead of pasting text.

This is a problem for all people that prefer and/or need to used ctrl-shift-v instead of ctrl-v to paste text, and then can't use clipboard manager to keep a cut+paste history.

**Comment by DHowett** [comment]
What would you like us to do about it? If your clipboard software can’t be reconfigured to use something other than Ctrl+V, and you need Ctrl+V to work in your connected client application... you may need new clipboard software. 

We have been discussing the options with the Windows clipboard team, and they don’t seem to have any ideas.

**Comment by KalleOlaviNiemitalo** [comment]
Oh it actually sends WM_KEYDOWN messages for Ctrl+V 😮 If I turn off "Enable Ctrl key shortcuts" in conhost of Windows 10 version 20H2 (OS Build 19042.928), then Windows+V cannot paste to that either.

Doesn't UWP support anything equivalent to WM_PASTE, which would indicate the intent regardless of key bindings?

**Comment by zadjii-msft** [comment]
We're actually tracking this discussion over in #322. It started as a discussion about "ditto", but expanded to a discussion of the Windows 10 "Cloud Clipboard" as well.

/dup #322
