### ISSUE TITLE
WT preview 1.8 crashes when running some AHK scripts

### ISSUE THREAD

**Issue by jmlucjav** [microsoft/terminal#9944]
I use wt to host neovim. It is crashing very often, I thought it was neovim, but finally looked in windows event viewer and I see its WT which fails. See such a log, I am in 1.8 preview.

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-04-25T08:29:04.4414387Z" /> 
  <EventRecordID>6156</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>lap</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>WindowsTerminal.exe</Data> 
  <Data>1.8.2104.13002</Data> 
  <Data>60762171</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.19041.906</Data> 
  <Data>2f2f77bf</Data> 
  <Data>c0000602</Data> 
  <Data>000000000010b2dc</Data> 
  <Data>3140</Data> 
  <Data>01d739ac3ef08dd7</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.8.1032.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>be5d7df6-b651-493d-9e9e-e44a216f2b97</Data> 
  <Data>Microsoft.WindowsTerminalPreview_1.8.1032.0_x64__8wekyb3d8bbwe</Data> 
  <Data>App</Data> 
  </EventData>
  </Event>
```

**Comment by zadjii-msft** [comment]
/feedback

(that'll help send us a crash with an actual stack trace to investigate)

**Comment by jmlucjav** [comment]
Cannot do that as Feedback is uninstalled and I cannot seem to install it from Store anymore. Next time I reinstall win10 I'll keep feedback hub.

**Comment by zadjii-msft** [comment]
Do you have specific repro steps? "neovim crashes often" is unfortunately not really enough to be able to investigate, and without a stack trace I'm not sure what else we can do about this one...

**Comment by jmlucjav** [comment]
I was hoping the eventviewer data would help. 
Regarding repro: it always happens when I am making managing wt windows with ahk scripts (quake style stuff).

**Comment by zadjii-msft** [comment]
Now, that's an even _more complicated_ repro. 
* Does it ever repro without running your AHK scripts?
* Does it repro when running your AHK scripts, but _without_ neovim?
* What script are you running _specifically_?

**Comment by jmlucjav** [comment]
> * Does it ever repro without running your AHK scripts?
I wouldn't say so

> * Does it repro when running your AHK scripts, but _without_ neovim?
I don't think so

> * What script are you running _specifically_?
as I said, home grown quake-like functionality

**Comment by zadjii-msft** [comment]
> > * Does it repro when running your AHK scripts, but without neovim?
> 
> I don't think so

Cool, we can eliminate that variable then.


> as I said, home grown quake-like functionality

Okay you gotta share the script with me so I can investigate what exactly it is that you're doing that's causing the Terminal to crash.
