### ISSUE TITLE
When changing tab color via keyboard shortcut, "unfocussed" color is used

### ISSUE THREAD

**Issue by NeilMacMullen** [microsoft/terminal#9945]
```
Windows Terminal Preview
Version: 1.8.1032.0
```

I love the ability to change the text and color of tab headers :-) I have set up a keyboard shortcut to 
allow quick access to the TabColorPicker.... 

```
"command": 
{
"action": "openTabColorPicker"
},
"keys": "ctrl+shift+c"
```
However, I've noticed that when invoked this way, the picker assumes the current tab is unfocussed and choose the "grayed" version of the color until the focus is manually changed or the mouse is moved over the header.

![ColorPickerFocus](https://user-images.githubusercontent.com/9131337/115990205-e7b71400-a5b9-11eb-9bcd-1a67d901fd41.gif)

**Comment by zadjii-msft** [comment]
I'm gonna label this as another variant of #8948. Whatever we're doing to set the tab color, MUX isn't very happy about.

/dup #8948

**Comment by NeilMacMullen** [comment]
Nice spot - agree this looks like a dup. :thumb:
