### ISSUE TITLE
Keybind sequences

### ISSUE THREAD

**Issue by ChrisTsou** [microsoft/terminal#9946]
# Description of the new feature/enhancement

Be able to bind key sequences.
example:
<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>c</kbd>: start the "close" sequence, then be able to release those keys and press:
<kbd>t</kbd> : close tab
<kbd>p</kbd> : close pane

so you have, 
ctrl+shift+c(lose), t(ab)
ctrl+shift+c(lose), p(ane)

this allows to make mnemonic bindings and it allows for more key combinations

# Proposed technical implementation details (optional)

- When a sequence starts it should probably timeout after some user defined time and/or be able to cancel it with esc
- I find tmux's way of doing this with key tables a nice solution

**Comment by skyline75489** [comment]
I use tmux myself and I don't hate the idea. Not sure this is technically possible with the current codebase, though..

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1334 for more discussion.

/dup #1334
