### ISSUE TITLE
The WT can't create a new tab based on the parent root when i onpen from the right click menu 

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [microsoft/terminal#9947]
# Description of the new feature/enhancement

The WT can't create a new tab based on the parent root when i onpen from the right click menu.
After update the new version, a content is created on my right click menu,which named "Open in windows terminal ".When I click it from "D:/myfile:" ,although the first page is base on my folder root which is "D:/myfile", the  root of new tab is "c:/windows/system32" again. It is unconvenient!! WISH TO BE SOLVED!!

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #8933 for more discussion.

/dup #8933
