### ISSUE TITLE
command line almost there

### ISSUE THREAD

**Issue by DanielPython2021** [microsoft/terminal#9948]
# Description of the new feature/enhancement
I open 15 tabs and run programs process data during hours and print during those hours. I am actually using pyautogui to generate tabs, write command lines on each one, change tab color an title. And it works ok (sometimes there are some errors). Recently I learn the command line feature is actually doing this work and I tested it and work very efficiently (I did not chek all features).  The probllem I found (perhaps I did not fount the solution that already exists) is that once the program running in the tab finishs the tab is closed and I lose the printed results (20.000 lines or more in each console). programs/tab titles/tab colors/etc.

See above.
# Proposed technical implementation details (optional)
My suggestion is that the default behaviour should not close the tab and might be a switch for closing it in the command line of creation of tabs/runing 

run a bat with the whole command line that gets up all the consoles (opens tabs, run programs and keep all the information available)
![wttabs](https://user-images.githubusercontent.com/83194624/116021554-cc322480-a61e-11eb-82f1-afcc57040da2.jpg)

**Comment by vefatica** [comment]
These options may be of interest.

![image](https://user-images.githubusercontent.com/61856645/116023440-15cc4080-a61a-11eb-886b-e334f4efa569.png)

**Comment by DanielPython2021** [comment]
I think that solves the problem. I found (not easily) the menu you show.
Perhaps tomorrow I can try to configure all tabs.

thank you 😀

**Comment by vefatica** [comment]
I'm glad it helps.  In the JSON file, you can get all profiles by putting it in "defaults".  The default setting can be overridden for specific profiles.

```
        "defaults": 
        {
            "closeOnExit": "never",
            // ...
      },
```

**Comment by zadjii-msft** [comment]
Great! Glad you got this figured out ☺️

**Comment by DanielPython2021** [comment]
Dear Mike, the first time I tested my computer freezed and I had to reset
it. I did not further tests until this weekend and everything worked fine
(I am not sure what happened before but I consider it a isolated case that
will not repeat). I have two questions:
1) When my programs end (launching them in this fashion (multiple consoles
form command line) there is an exit code 0 and the console can not be used
again. Is it possible to configure the console to return the command prompt
as is usually done at the end of running a program?

2) Is there a linux version of WINDOWS TERMINAL? Not to be run in WSL but
in linux.

regards,
Daniel

**Comment by zadjii-msft** [comment]
1. I'm pretty sure the `/k` flag in `cmd.exe` will do what you're looking for. `cmd.exe /k dir` will execute a `dir`, then return to the cmd prompt. I'm sure there's a different way of doing it for PowerShell, but I'm more of a cmd.exe person myself 😄 
2. Nope, and there's a whole plethora of threads elsewhere on the repo as to why that is.

**Comment by DanielPython2021** [comment]
I am reading your answer.

About... gives this version.

Windows Terminal
Versión: 1.11.2921.0

**Comment by DanielPython2021** [comment]
adding "-p cmd" seems to solve the problem. I have to wait until all
process is done but at the beginning I have the proper background color and
the correct characters per line, so the aspect was corrected. I will wait
the processes to end to check how windows closes, but seems to correct that
also since the default is "closeOnExit": "graceful" and my setting is for
"closeOnExit": "never".

If so, I am back in my previous condition of operation. => SOLVED.

Thank you again, Daniel. 😀
