### ISSUE TITLE
 The release title  do not match  release tag  in 1.7.1091.0

### ISSUE THREAD

**Issue by Tsuj100** [microsoft/terminal#9951]
The release title  do not match  release tag  in 1.7.1091.0

**Comment by skyline75489** [comment]
What do you mean by "release title" exactly?

**Comment by Tsuj100** [comment]
![image](https://user-images.githubusercontent.com/38718810/116041096-65088480-a69f-11eb-90d0-1e25bdba7a1e.png)

**Comment by skyline75489** [comment]
Ha. Good catch. Let's see if @DHowett wants to do something about it.

**Comment by zadjii-msft** [comment]
Thanks for the catch! I've gone ahead and fixed the typo
