### ISSUE TITLE
Proposed Functionality Regarding Transparency

### ISSUE THREAD

**Issue by nrloucks** [microsoft/terminal#9952]
# Preface
Regarding Windows Acrylic.
I've looked into this as far as the internet could take me before posting here. From what I've read it's my understanding that Windows Acrylic's policy for in || out of focus windows is the reason that the background is transparent when the window is active and opaque when it out of focus. It is also my understanding that there is no real way to make it transparent regardless of focus because of this overlying policy.

# Description of the new feature/enhancement ############################################
Reverse the function of Windows Acrylic in Windows Terminal.
When WTerm window is:

    In focus: background is always 100% opaque.
        Having no transparency is often better suited to actively working in the terminal. When the user brings the
        window in focus it goes fully opaque allowing for the easiest reading/entering of text regardless of the 
        color of the window behind it.**
    
    Out of focus: User definable, or constant, transparency.
        When the user clicks out of focus the background becomes partially transparent. 

Essentially reversing the way Acrylic functions as it is now with respect to background transparency.

**With anything more than a very minimal transparency I always find myself struggling to read the text over whatever color window happens to be behind the terminal, regardless of the text color I'm using at the time. Everyone loves a transparent terminal window, so having transparency when the window is off to the side is the perfect time to enjoy that feature. 

# Proposed conceptual implementation details ############################################
( I'm not sure how the program interfaces with windows acrylic. I don't really have any software development experience, I'm in electrical engineering so my programming knowledge is largely with lower level programs and the like. That said, take my idea with a grain of salt ). 

It's my understanding that there isn't a clear cut way to allow in+out of focus background transparency with the way acrylic manages the transparency effects. Presumably it doesn't want to waste resources on transparency effects for windows that you aren't actively using. Just thinking maybe there's a sneaky way to reverse when it thinks the window is in focus so the acrylic works a bit more intuitively out of the box.

If there is a value that tells Win. Acrylic the window is || is not in focus, tell acrylic the opposite.
hypothetically if there's some flag inFocus thats true or false and various things happen depending on the value of that flag finding a way to tell only windows acrylic that inFocus=false when the user is actively using the terminal and vice versa.

Hoping something along those lines may be possible, albeit likely much more complicated in actual implementation.

Though this is simply a cosmetic feature, I know it's important to a significant percentage of people who use WT, just based on the number of github bug reports that come up as a result of a quick google search on the matter. Most of which consist of people asking questions and/or reporting what they had thought was a bug regarding the way the Acrylic background works. 

Thanks for reading, feel free to let me know what you think. I'm a big fan of Windows Terminal, its something windows has been in dire need of forever. Thanks for all your work and making it what it is today.

Best
nathan

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7158 for more discussion.

/dup #7158
