### ISSUE TITLE
Drop down menu scrolls past terminal window

### ISSUE THREAD

**Issue by nexes** [microsoft/terminal#9958]
# Description of the new feature/enhancement
When using the drop down menu in settings(GUI) the drop down menu will move past the window when scrolling down. This happens on all drop down menus in settings.

e.g. Startup->Default profile
 
![terminal1](https://user-images.githubusercontent.com/178968/116122362-886b0980-a676-11eb-802d-d5e6411c0f9f.png)

![terminal2](https://user-images.githubusercontent.com/178968/116122380-8ef98100-a676-11eb-8550-8a8421758ef6.png)

Windows Terminal Version: 1.7.1033.0
Windows 10 Version: 20H2 (19042.928)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #9320 for more discussion.

/dup #9320
