### ISSUE TITLE
Sometimes, saving a setting in the UI doesn't actually apply

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#9962]
The minimal repro:

* Install powershell core, at least one of them
* Close the Terminal.
* Delete all the settings.json files.
* Open the Terminal, go to the SUI, go to the "Appearance" of the Powershell Core.
* Change scrollbar state to hidden.
* Hit Save.

At this point, the SUI will reload. The scrollbar state didn't apply, and now you've got a mysterious "Default" profile. Also, the `setting.json` is now corrupted. It's now got 

```
{},
{
  "scrollbarState": "hidden"
}
```

slammed in the profiles list, which is garbage data.

* [ ] Figure out why the setting is blasting off to space.
* [ ] Add a mitigation to ignore profile snippets without a GUID

/cc @carlos-zamora. 

Now, I'm gonna close all the threads we think are a dupe of this one.

**Comment by Krrishdhaneja** [comment]
hey @zadjii-msft when I deleted the whole `setting.json` and got a new one generated, then the default profile was removed and it didn't reappear.

**Comment by zadjii-msft** [comment]
@Krrishdhaneja That sounds like a totally different issue. Mind filing a new issue? (make sure to include version numbers, which profile you were expecting to see generated, your `settings.json`, etc.)

**Comment by Krrishdhaneja** [comment]
> 
> 
> @Krrishdhaneja That sounds like a totally different issue. Mind filing a new issue? (make sure to include version numbers, which profile you were expecting to see generated, your `settings.json`, etc.)

I don't mind making it, but I am rather saying that it might be the solution to that default json profile maybe, by deleting the `settings.json` and then make changes in the regenerated one to get back older settings?

**Comment by htcfreek** [comment]
@zadjii-msft 
Does the pr fixes the bug that new profiles don't have a guid?

Every new profile I generate doesn't have a guid. So if you ignore these profiles you create a new problem. (How will this be fixed on updating to the new release?)

**Comment by Krrishdhaneja** [comment]
Hey, today I encountered the issue again, and I think what could be possible reason for that is maybe when the modifications are made using SUI, the changes aren't registered in the profile we wanted/made changes for, but rather the SUI creates a completely new profile with those properties.

**Comment by zadjii-msft** [comment]
@Krrishdhaneja Yep, that's basically the root cause of what we fixed in #9964


The "ignore snippets without a guid" mitigation should only apply to snippets without a name or guid. When a profile doesn't have an explicit guid, we generate one for that profile based on the name. in the case of the `{}` profile, there's no name or guid, so we can be relatively sure that blob isn't actually a valid profile.

I also think we didn't end up doing that, so it's not a big deal.
