### ISSUE TITLE
Highlight terminal output based on regex pattern

### ISSUE THREAD

**Issue by Agaspher20** [microsoft/terminal#9965]
# Description of the new feature/enhancement

That would be really handy to have an ability to apply some custom highlighting to terminal output.
For example when I read logs generated by some application I want to highlight particular feature name I'm interested in. So if logs of this feature start with Info: [Feature name] log message, I want to highlight "[Feature name]" with yellow.

That should be an ability to specify various highlighting rules. E.g. I have the following outputs
error: [feature 1] error message here
warning: [feature 2] some another message
info: [feature 3] yet another message

In this case I want to highlight "error:" with red, "warning:" with yellow, "info with green and "debug" with blue. And of course that would be cool if I highlight different features with different colors.

Just to emphasize. That is not mandatory that patterns are at the beginning of the string. It could be in any part of the string.

# Proposed technical implementation `details`

A set of rules in `settings.json` which associate regex pattern with color. E.g.:

```
{
    "highlightRules": [
        "pattern": "^error:",
        "color": "red"
    ], [
        "pattern": "\[feature name\]",
        "color": "#deab1f"
    ], [
        "pattern" "^(?:\d{2,4}-?)+\s(?:\d{2,3}[:\.]?)+", // date pattern
        "color": "#34ebe1"
    ]
}
```

**Comment by skyline75489** [comment]
Similar request: #7561

**Comment by skyline75489** [comment]
#7561 and #3920 both focus on highlighting *search* result. Do people really want to highlight output (of certain pattern) *all the time* ? I don't know. I feel colored output is good enough for me personally.

**Comment by Agaspher20** [comment]
> 
> 
> #7561 and #3920 both focus on highlighting _search_ result. Do people really want to highlight output (of certain pattern) _all the time_ ? I don't know. I feel colored output is good enough for me personally.

Yes that would be good to highlight output on regular basis and the difference of this request from #7561 is that you wouldn't have any dialog open when output is highlighted.

That would be also cool if that could look more like code highlighting then search results highlighting.

**Comment by zadjii-msft** [comment]
Yea, generally we're tracking this in #3920 and linked threads. I know  #8294 mentions "links", but I think a lot of what that's tracking would apply to even not links.

/dup #7561
/dup #3920 
/dup #8294

**Comment by jonny64** [comment]
* mobaxterm has this feature
https://stackoverflow.com/questions/64391031/how-to-use-customize-syntax-highlighting-on-mobaxterm
* it has by default pretty good defaults: highlight err* warn* etc

impact: find errors faster

this is not the same as highlight find results, just try it
