### ISSUE TITLE
Profile IDs for wt command line

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#9967]
# Description of the new feature/enhancement

Please add a feature to define profile ids/short names for profiles.

I don't want to type `wt.exe -p "Eingabeaufforderung"`. Something like `wt.exe -p "cmd"` would be smarter.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
You could always rename your "Eingabeaufforderung" to just `cmd` if you wanted. Does that not work for you?

**Comment by htcfreek** [comment]
Yes it works. Wasn't sure if it is possible for auto-generated profiles.

**Comment by zadjii-msft** [comment]
Yep, it sure is!
