### ISSUE TITLE
Classic Command Prompt consumes high CPU on long log stream 

### ISSUE THREAD

**Issue by brunoborges** [microsoft/terminal#9969]
### Windows Build Number

Windows 10

### Processor Architecture

x64

### Memory

16 GB

### Storage Type, free / capacity

SSD 512 GB

### Relevant apps installed

Command Prompt

### Traces collected via Feedback Hub

https://github.com/microsoft/java-wdb/issues/23

### Isssue description

"if I run a maven build in a cmd window it seems that screen output eats more CPU than the actual build."

https://github.com/microsoft/java-wdb/issues/23

### Steps to reproduce

Build a Java project that will produce significant amount of build log.

Example: https://github.com/spring-projects/spring-boot

### Expected Behavior

Low CPU.

### Actual Behavior

High CPU.

**Comment by zadjii-msft** [comment]
@brunoborges Could you be more specific as to which build of Windows 10 you're using? Conhost has had a lot of updates over the last 6 years of Windows 10, with a lot of perf improvements along the way. 

Are you using the legacy console?
![image](https://user-images.githubusercontent.com/18356694/116310962-4920e380-a770-11eb-9800-f075e5fe499a.png)

**Comment by zadjii-msft** [comment]
For the record, OP in that reddit thread mentioned

> Please note that I'm using Windows 7 so maybe some issues are already improved. Also my issues may stem from my way of doing things and there might be better ways.

And _yea_, the console host has gotten an enormous amount of investment since Windows 7. I'm dangerously close to just closing this as "Fix-Available" 😄

**Comment by DHowett** [comment]
Sorry, are you reporting an issue from somebody who's running Windows 7? ☹️
