### ISSUE TITLE
Feature Request: History Size Infinity

### ISSUE THREAD

**Issue by ganluo960214** [microsoft/terminal#9975]
# Description of the new feature/enhancement

History Size Infinity

**Comment by skyline75489** [comment]
Is #1410 what you looking for?

**Comment by ganluo960214** [comment]
@skyline75489 yes

**Comment by skyline75489** [comment]
Great! Make sure to search for duplicate issues before filling new ones. I'll close this and please subscribe #1410 instead.

**Comment by ganluo960214** [comment]
@skyline75489 I searched but not found this one.
