### ISSUE TITLE
Do we need the Contributor Over Time chart?

### ISSUE THREAD

**Issue by starsz** [microsoft/terminal#9976]
Hi, we have generated a chart of the contributor over time, which may be helpful to you.

You can take a look here:
https://contributor-graph-api.apiseven.com/contributors-svg?chart=contributorOverTime&repo=microsoft/terminal

**Comment by zadjii-msft** [comment]
Hey thanks for making that! It looks pretty neat. If I'm not mistaken, our management uses something just like that (but in powerbi) for tracking our "repo health" or something. Thanks anyways!
