### ISSUE TITLE
Settings UI: bad spacing between pivot header and its content

### ISSUE THREAD

**Issue by vinderguy** [microsoft/terminal#9978]
# Description of the new feature/enhancement

There should be more space between the pivot tab header and its content. I'm am not sure if it is against Fluent design guidelines but IMHO the second version looks significantly better. This minor UI tweak should take less than 2 minutes to apply.

**Before:**

![before](https://user-images.githubusercontent.com/26736457/116431630-41cd0900-a848-11eb-9dc5-dffc613da147.png)

**After:**

![after](https://user-images.githubusercontent.com/26736457/116431650-44c7f980-a848-11eb-9407-aa610fc49ada.png)

# Proposed technical implementation details (optional)

`<PivotItem x:Uid="Profile_General" Margin="12,12,12,0">` or something like this. Do it for every `PivotItem` in `ProfilesPivot`
File: https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalSettingsEditor/Profiles.xaml

**Comment by lhecker** [comment]
Actually most elements already have margin specified.
In order to give the first element the same visual 29px margin to the blue Pivot bar, as other element sections have between each other we can just modify those:
```diff
diff --git a/src/cascadia/TerminalSettingsEditor/Profiles.xaml b/src/cascadia/TerminalSettingsEditor/Profiles.xaml
index 16b53961..59163d62 100644
--- a/src/cascadia/TerminalSettingsEditor/Profiles.xaml
+++ b/src/cascadia/TerminalSettingsEditor/Profiles.xaml
@@ -78,3 +78,3 @@
                         <local:SettingContainer x:Uid="Profile_Name"
-                                                Margin="0,0,0,24"
+                                                Margin="0,22,0,0"
                                                 Visibility="{x:Bind State.Profile.IsBaseLayer, Mode=OneWay, Converter={StaticResource InvertedBooleanToVisibilityConverter}}">
@@ -87,3 +87,3 @@
                                                 x:Uid="Profile_Commandline"
-                                                Margin="0,0,0,24"
+                                                Margin="0,24,0,0"
                                                 ClearSettingValue="{x:Bind State.Profile.ClearCommandline}"
@@ -104,3 +104,3 @@
                                                 x:Uid="Profile_StartingDirectory"
-                                                Margin="0"
+                                                Margin="0,24,0,0"
                                                 ClearSettingValue="{x:Bind State.Profile.ClearStartingDirectory}"
@@ -242,2 +242,3 @@
                             <TextBlock x:Uid="Profile_TextHeader"
+                                       Margin="0,19,0,0"
                                        Style="{StaticResource SubtitleTextBlockStyle}" />
@@ -711,3 +712,3 @@
                         <local:SettingContainer x:Uid="Profile_SuppressApplicationTitle"
-                                                Margin="0"
+                                                Margin="0,22,0,0"
                                                 ClearSettingValue="{x:Bind State.Profile.ClearSuppressApplicationTitle}"
```

I personally agree with such a change. I'd also look forward to having a style guide for this project (in the far future), which would clearly specify the margins between controls, labels, titles, borders, etc. (Because as you can see in the diff you have to give the TextHeader element a different margin from the rest.)

**Comment by zadjii-msft** [comment]
You know, this isn't really going to be an issue once #11720 lands, since _there won't be a pivot anymore_ 😅
