### ISSUE TITLE
"Failed to load settings" on startup (probably after upgrade)

### ISSUE THREAD

**Issue by JHBonarius** [microsoft/terminal#9979]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

Upgrade from version (don't remember, de file dates say March 2nd 2021) to 1.7.1033.0 (through the Microsoft Store) and open the app.

### Expected Behavior

Program to open normally.

### Actual Behavior

![afbeelding](https://user-images.githubusercontent.com/36847155/116414851-21e21900-a839-11eb-8989-15f141c1f371.png)

After inspecting my settings.json (comments in JSON? that's not legal JSON :P ) I found that there were illegal characters in the first line (before the comments), which I hadn't put there. It looked to be _part of_ my user path or so. Alas, I removed it and didn't think of saving. But it was something like:
```
C:\User\Joch// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
...etc
``` 

Anyhow, just to let you know. After removing it, it's fine now.

**Comment by zadjii-msft** [comment]
Wait so, your settings are actually totally fine now? Glad you got it sorted out! I wonder how that text got there...
