### ISSUE TITLE
Open panes with a specific profile

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#998]
You can only open a pane with the default profile

I left space for adding support for opening a specific pane, but it didn't really seem like there was a good keychord for doing this currently. Maybe if we added support for multi-key keychords, then it'd make more sense.

EDIT:

With #3391 merged, this is pretty possible now.

I'd really like for this to work like the following:

```json
    { "command": "splitHorizontal", "keys": [ "alt+shift+-" ] },
    { "command": "splitVertical", "keys": [ "alt+shift+plus" ] },

    { "keys": [ "alt+1" ], "command": { "action": "split", "style": "horizontal" } },
    { "keys": [ "alt+2" ], "command": { "action": "split", "style": "vertical", "profile": "{some-guid}" } },
    { "keys": [ "alt+3" ], "command": { "action": "split", "style": "horizontal", "type": "duplicate" } },
    { "keys": [ "alt+4" ], "command": { "action": "split", "style": "vertical", "type": "prompt" } },
```

The first two entries are the legacy style keybindings for panes. 

The next four represent 4 different ways of opening a new pane:
* [x] <kbd>alt+1</kbd>: Open a new pane with the default profile. This is the current behavior.
* [ ] <kbd>alt+2</kbd>: Open a new pane with the profile with guid "{some-guid}". (this issue)
* [ ] <kbd>alt+3</kbd>: Open a new pane with the same profile as the currently focused pane. (this is tacked in #1756)
* [ ] <kbd>alt+4</kbd>: Open a new pane by prompting the user first. (this is tacked in #3586)

This issue will track just that second option.

**Comment by invy** [comment]
There are few options (inspired by i3)"
1. Popup Dialog:
 - Specifig key combinatin will trigger a popup dialog with all profiles, where user can select specific profile.
2. Ability to rearrange tabs with key combinations (inclusive ability to transform tab into a tile in specific window)
3. i3 way: enable specifyc tiling mode (vertical/horizontal), then DMenu like: just search for specific profile (or even a specific command, which can be executed in specific profile)...
