### ISSUE TITLE
Disable "follow link"

### ISSUE THREAD

**Issue by 89z** [microsoft/terminal#9981]
Since some new version, every single link the output is underlined, with this tooltip:

~~~
Ctrl+Click to follow link
~~~

I found this:

https://github.com/microsoft/terminal/blob/65b22b9abba26fa94150505cee4444dcb4e42182/src/cascadia/TerminalControl/Resources/en-US/Resources.resw#L178-L180

but I dont see any documentation on how to disable this.

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/issues/5001

https://github.com/microsoft/terminal/issues/9981
https://github.com/microsoft/terminal/pull/7420
https://github.com/microsoft/terminal/pull/8293

**Comment by 89z** [comment]
Well since it seems no way is currently available to disable this, here is the last version without hyperlink support:

https://github.com/microsoft/terminal/releases/tag/v1.4.3243.0

**Comment by DHowett** [comment]
Downgrading seems like the nuclear option. Mind me asking why you hate it so much?

**Comment by DHowett** [comment]
(You clearly hate it enough to track down and comment on every related issue, so I'm compelled to figure out why...)

**Comment by 89z** [comment]
@DHowett I dont like it. Its distracting. I dont want to be hovering over some text, or worse, in the process of selecting some random text from the output, only to have every single link that happens to be in the output underlined. Not only underlined, but underlined **on hover**, so its essentially animating my terminal output. I dealt with it for a week or so, but I finally realized that its just distracting and I hate it.

So I was pretty upset to find out that it was just rolled out, without even and option to disable.

**Comment by 89z** [comment]
@DHowett I dont like it. Its distracting. I dont want to be hovering over some text, or worse, in the process of selecting some random text from the output, only to have every single link that happens to be in the output underlined. Not only underlined, but underlined **on hover**, so its essentially animating my terminal output. I dealt with it for a week or so, but I finally realized that its just distracting and I hate it.

So I was pretty upset to find out that it was just rolled out, without even an option to disable.

Think about it like this. `cmd.exe` was released in the 80s [1], so you potentially have people who have been using the Microsoft Terminal **for decades** without hyperlink support. Then last year, you just add it with no option to disable. Cant you understand how some people might not like that, that maybe they just dont need or want that?

1. https://wikipedia.org/wiki/Cmd.exe

**Comment by PankajBhojwani** [comment]
Hm, might be time to reopen #8293 then?

**Comment by zadjii-msft** [comment]
@PankajBhojwani Sure thing, we can add that to the backlog. We won't be able to land extensions till 2022 at the earliest, so best to provide some option sooner rather than later.

**Comment by j4james** [comment]
I think I may have suggested this before, but I'm quite partial to Mintty's way of doing this, where the link effect is only shown if you're actually holding down the ctrl key when hovering. That way you still have access to the functionality if you need it, but it doesn't get in your way when you aren't actually trying to click a link.

I don't know if that would satisfy the OP though, and I'd also be happy with just having an option to turn the links off.

**Comment by 89z** [comment]
@j4james ideally I would just like to totally turn of the pattern detection code. I assume its using regular expressions, so theres bound to be some overhead there. But your solution would at least be better than the current state. I am locked into `v1.4.3243` until things change.

**Comment by 89z** [comment]
This is not fixed with https://github.com/microsoft/terminal/releases/tag/v1.8.1444.0, and I dont want to use a preview version. So I will continue to use old version.

**Comment by DHowett** [comment]
That is your right. We fairly strictly observe a policy of not backporting *new features* and especially not *new settings* unless they have been validated in the public preview.

Thanks for letting us know.
