### ISSUE TITLE
Window Resize causing rendering issues

### ISSUE THREAD

**Issue by MhammadDayeh** [microsoft/terminal#9982]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

I know that this problem has been opened before, and its a duplicate, I am not able to solve the problem, I tried some of the solutions, someone said in another post that changing the historySize from 90000 to 9000, but in this version its already on 9000, I have enabled redraw entire screen option.

To reproduce this problem, I resize the window, and the text goes mayhem, all glitched, this sometimes happens also when I split the powershell in to two (Alt Shift +).

https://user-images.githubusercontent.com/42265793/116483622-7bc5fb80-a898-11eb-85f7-347a4369074d.mp4

![Capture](https://user-images.githubusercontent.com/42265793/116483710-ab750380-a898-11eb-8fdb-02e999051cad.PNG)

### Expected Behavior

Text should not be glitched after resizing.

### Actual Behavior

https://user-images.githubusercontent.com/42265793/116483622-7bc5fb80-a898-11eb-85f7-347a4369074d.mp4

![Capture](https://user-images.githubusercontent.com/42265793/116483710-ab750380-a898-11eb-8fdb-02e999051cad.PNG)

Every time this happens I have to restart the terminal and its been happening ever since I started using windows terminal when its released.

**Comment by zadjii-msft** [comment]
Woah, that's way more batty than anything I've seen in the related issues before. Could you share your vim config? That seems like something that's playing into how bad the state of the buffer gets

**Comment by MhammadDayeh** [comment]
Hi @zadjii-msft , I dont really think that vim has something to do with this, because this glitch happens without even vim running, in the video I provided I just ran vim as an example of what would happen while doing basic tasks, but I will still provide you with what you are asking for. It is vim 8 for windows not WSL, I will post the vimrc.

**Comment by zadjii-msft** [comment]
The vimrc isn't that important if that's not critical to the repro. If you've got a specific set of steps that'll repro the glitch, that'll work too. I just need something that I can build a test around 😝

**Comment by MhammadDayeh** [comment]
Welp, all what I do is that I literally just resize the window with my mouse, after some time of using the terminal, the glitches happen (sometimes the glitch does not occur until resizing the window more than once), this does not happen at all if the window is not resized. Also this glitch does not always happen, after some search I started to think that the problem is from my end (maybe GPU rendering problem.. idk), but I still would like to know your thoughts.

**Comment by j4james** [comment]
Maybe I'm not understanding the issue, but this just looks to me like a variant of the "exact wrap" bug (#3088). I can get the same effect by opening vi and resizing the window a bit. If you look at the scrollback at the point it's going to be a mess. Part of the problem is also that conpty doesn't pass through the alt buffer request (#381). If this resizing is happening in a full screen app (i.e. using the alt buffer), then it should never be polluting the scrollback, so you wouldn't typically notice the wrapping problems (except as a brief flash before the screen redraws).

**Comment by MhammadDayeh** [comment]
@j4james I can see that when vim is running, upon resizing the window I can see the split second of text wrapping (as I refer to as glitching) but then the buffer redraws and everything looks normal. If you see the video I provided, I am not sure why it sometimes happens that the text overlap and create unreadable mess, even after exiting vim, powershell sometimes seem to be glitching, and after pressing enter multipul times the buffer goes back to normal. Today, till now the buffer did not glitch, but it does happen as I managed to record it.

**Comment by MhammadDayeh** [comment]
https://user-images.githubusercontent.com/42265793/116607547-314d8900-a943-11eb-837a-07d51b7ee608.mp4

It happened again lol, I was in Vim, I resized my window inside Vim, I exited vim and this happened, I recorded it.

**Comment by DHowett** [comment]
This definitely looks like the exact wrap bug. Happens most often with vim because it reads and prints back the entire screen buffer (on Windows) which destroys our line wrapping detector.

/dup #3088

**Comment by MhammadDayeh** [comment]
@DHowett Thanks.
