### ISSUE TITLE
Nicer tab titles

### ISSUE THREAD

**Issue by catamphetamine** [microsoft/terminal#9983]
Tab titles are currently rendered rather dull:

![image](https://user-images.githubusercontent.com/477167/116486583-ac0c9a80-a896-11eb-886f-3dd858f7299d.png)

Compare to `cmder`:

![image](https://user-images.githubusercontent.com/477167/116486623-baf34d00-a896-11eb-8424-bb8f08927518.png)

Much more prominent, much more eligible.

You may close this once you've opened it.

**Comment by catamphetamine** [comment]
A bolder font weight and maybe a slightly larger font size would have fixed it.

**Comment by skyline75489** [comment]
I think #3327 covers this?

**Comment by zadjii-msft** [comment]
It sure does, thanks!

/dup #3327
