### ISSUE TITLE
Multiple Tabs shown as focus when focussing with wt focus-tab -t 0

### ISSUE THREAD

**Issue by VincentSchippefilt** [microsoft/terminal#9985]
### Windows Terminal version (or Windows build number)

10.0.19042.928

### Steps to reproduce

This is my command to open wt : 
`wt new-tab --profile PowerShell --startingDirectory o-spreadsheet; new-tab --profile Ubuntu --startingDirectory \\wsl$\Ubuntu\home\odoo\odoo ; split-pane --profile Ubuntu --startingDirectory \\wsl$\Ubuntu\home\odoo\enterprise; focus-tab -t 0`

### Expected Behavior

only one tab is focussed.

### Actual Behavior

and the result is this :
![image](https://user-images.githubusercontent.com/7260798/116513683-3fab8e80-a8ca-11eb-8776-838283136369.png)
Both tabs looks focussed.

After hovering over them, they take their correct focussed/unfocussed color: 
![image](https://user-images.githubusercontent.com/7260798/116513807-69fd4c00-a8ca-11eb-89ae-2f8c6b978f8c.png)

**Comment by zadjii-msft** [comment]
You know, I'm positive we have another issue tracking this somewhere. It's been happening for a while now, but it's not totally clear why. This is very similar to #8948, but a little different. Both are "The tab has the wrong color till you mouse over the tabs", though that one seems to be the shadow on top of the tabs.

**Comment by zadjii-msft** [comment]
Found it!

/dup #9595
