### ISSUE TITLE
That Terminal can be pulled up and down from the top of the screen with a special hotkey, and it's transparent

### ISSUE THREAD

**Issue by jefer94** [microsoft/terminal#9989]
Tilda and Guake can toggle the window view, it can be called with one hotkey and open the terminal in anywhere, with this feature you can are seeing one youtube video and toggle the terminal for install one package and quickly return to youtube. Could be great that Windows Terminal support this feature

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+Tilda+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #653 for more discussion.

/dup #653
