### ISSUE TITLE
If you click on the separators between panes, then no panes will be focused

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#999]
Self explanatory. This is related to #528, but is definitely different.

How does this interact with #994? If we make the separator a margin, then this won't be an issue.

**Comment by glen-84** [comment]
(two small errors in the issue title: `separator's` -> `separators`, `on` -> `no`)

**Comment by zadjii-msft** [comment]
@glen-84 thanks :) That's what I get for typing up 10 issues in a text file and posting them without spellchecking first

**Comment by varemenos** [comment]
May I include that clicking and dragging that same area (screenshot included), theoretically move the terminal (right?).
![Capture](https://user-images.githubusercontent.com/626343/61190415-21948000-a69c-11e9-93b9-ebfeed2b7abc.PNG)

**Comment by DHowett-MSFT** [comment]
@varemenos does that seem related to "split panes" at all? #564.

**Comment by varemenos** [comment]
@DHowett-MSFT yes, it's precisely that.
